[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SitePop"
version = "0.0.1"
authors = [
  { name="Byron Himes", email="byro93@live.com" },
]
description = "Generates html, css, and js files through python. Mostly a novelty, but can be used for rapid template generation."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
