[package]
name = "ndinterp_py"
version = "0.0.1"
authors = ["Alessandro Candido <alessandro.candido@sns.it>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/AleCandido/ndinterp"
readme = "README.md"
categories = ["science"]
description = "N-dimensional interpolation library - python interface"

[lib]
name = "ndinterp"
crate-type = ["cdylib"]

[dependencies]
ndinterp = { path = "local_dependencies/ndinterp" }
pyo3 = { features = ["extension-module"], version = "0.16.4" }
