[tool.poetry]
name = "utrello"
version = "0.2.0"
description = ""
authors = ["Davi Koscianski Vidal <davividal@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
utrello = "src.utrello:main"

[tool.semantic_release]
version_variable = [
    "src/utrello/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "master"
upload_to_pypi = true
build_command = "pip install poetry && poetry build"