[tool.poetry]
name = "primapy-es"
version = "0.1.0"
description = "Safety placeholder"
authors = ["Riccardo Sayn <riccardo.sayn@prima.it>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
