[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "mistly"
version = "0.0.6"
authors = [
  { name="Saba Umikashvili" },
  { name="Lasha Loria" },
]
description = "Search for songs and fetch lyrics in your terminal"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
	"requests",
	"beautifulsoup4",
	"rich",
	"textual"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Graphity/Mistly"
"Bug Tracker" = "https://github.com/Graphity/Mistly/issues"

[project.scripts]
mistly = "mistly.__main__:Mistly.run"
