# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "strawhat"
version = "0.2.0"
description = "Wrapper module for aws boto3"
readme = "README.md"
authors = [{ name = "Mridul Ahluwalia", email = "ahluwaliamridul@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["strawhat", "aws", "boto3"]
dependencies = [
    "jmespath",
    "six",
    "python-dateutil",
    "urllib3",
    "botocore",
    "s3transfer",
    "boto3",
]
requires-python = ">=3.9"

[tool.bumpver]
current_version = "0.2.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]
"src/strawhat/__init__.py" = ["{version}"]
