[build-system]
requires = ["setuptools>=45", "setuptools_scm>=6.2", "setuptools_scm_git_archive"]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "smap_window/version.py"

[tool.black]
target-version = ['py38', 'py39', 'py310']
exclude = '''
(
  \.egg
  | \.git
  | \.venv
  | build
  | dist
)
'''