
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-28T10:08:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "497a7e27ffd936210e71fa69374bef57baf7317a",
 "version": "2.2.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
