[tool.poetry]
name = "django3-feedparser"
version = "2.0.1"
description = "A Django app using feedparser to fetch and parse a feed to render it from a template."
homepage = "https://github.com/ImaginaryLandscape/django3-feedparser"
readme = "README.rst"
authors = ["David Thenon <dthenon@emencia.com>"]
maintainers = ["Imagescape <info@imagescape.com>"]
license = "MIT"
packages = [
    { include = "django_feedparser" },
]

[tool.poetry.dependencies]
python = "^3.7"
six = "^1.16.0"
requests = "^2.28.0"
feedparser = "^6.0.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
