
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-22T08:57:21-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4cc06be87994bbbc272d44d560d9b2e567f07f3",
 "version": "v1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
