[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "loopui"
version = "0.1"
authors = [
  { name="Guillaume Pirot", email="guillaume.pirot@uwa.edu.au" },
]
description = "Uncertainty Indicators for ensemble of 3D voxets"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Loop3D/loopUI"
"Bug Tracker" = "https://github.com/Loop3D/loopUI/issues"

