[tool.poetry]
name = "vincaweb"
version = "0.1.1"
description = ""
authors = ["Oscar Laird <olaird25@gmail.com>"]
license = "CC0"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.1.2"
vinca = "^2.4.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
