[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ican"
description = "Yet another deployment system.  Manage version bumping, git, etc."
readme = "README.md"
keywords = ["api", "auth"]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    'importlib-metadata; python_version<"3.8"',
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "ican.__public_version__"}

[project.scripts]
ican = "ican.cli:entry"

[project.urls]
homepage = "https://github.com/jthop/ican"
repository = "https://github.com/jthop/ican"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''