app_name: algora-sdk
environment: local
version: 0.0.BETA

local:
  urls:
    algora: https://api.algoralabs.com
    keycloak: https://auth.algoralabs.com/auth/admin/realms/production

production:
  urls:
    algora: https://api.algoralabs.com
    keycloak: https://auth.algoralabs.com/auth/admin/realms/production
