
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-17T23:14:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6858fe23af29cb28379723175895c9d02fdca51",
 "version": "2.7.3.dev20220622"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
