stages:
  - pre-commit
  - review
  - test
  - deploy

before_script:
  - python -V
  - pip install tox

pre-commit:
  stage: review
  image: registry.gitlab.com/gamechaingers/docker-images/gitlab/django
  variables:
    PRE_COMMIT_HOME: "${CI_PROJECT_DIR}/.cache/pre-commit"
  cache:
    paths:
      - "${PRE_COMMIT_HOME}"
  before_script:
    - apt-get install -y ruby-dev
    - pip install pre-commit
  script:
    - pre-commit run --all-files

.base-test:
  needs: []
  stage: test
  before_script:
    - pip install tox

test-py37:
  extends: .base-test
  image: python:3.7-buster
  script:
    - tox -e py37
    - bash <(curl -s https://codecov.io/bash)

test-py38:
  extends: .base-test
  image: python:3.8-buster
  script:
    - tox -e py38
    - bash <(curl -s https://codecov.io/bash)

test-py39:
  needs: []
  stage: test
  image: python:3.9-buster
  script:
    - tox -e py39
    - bash <(curl -s https://codecov.io/bash)

test-py310:
  needs: []
  stage: test
  image: python:3.10-buster
  script:
    - tox -e py310
    - bash <(curl -s https://codecov.io/bash)

deploy-pypi:
  stage: deploy
  image: python:3.7-buster

  before_script:
    - pip install twine wheel

  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags

danger:
  image: ruby:2.7-buster
  needs: []
  stage: review
  before_script:
    - gem install danger-gitlab
  script:
    - danger --fail-on-errors=true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

include:
  - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"
