image: registry.gitlab.com/gamechaingers/docker-images/gitpod/django:latest
gitConfig:
  pull.rebase: "true"
tasks:
  - name: "pre-commit"
    command: |
      pip install pre-commit Commitizen
      pre-commit install && pre-commit install-hooks

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false

vscode:
  extensions:
    - ms-python.vscode-pylance
    - njpwerner.autodocstring
    - vscode.markdown
    - PKief.material-icon-theme
    - eamodio.gitlens
    - oderwat.indent-rainbow
    - magicstack.MagicPython
    - donjayamanne.python-extension-pack
