default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.(min\.css|min\.js|mo)$
      - id: requirements-txt-fixer
        files: requirements(-[a-z]+).in
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: remove-tabs
        exclude: Makefile
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        exclude: "CHANGELOG.md"
  - repo: https://github.com/thibaudcolas/curlylint
    rev: "v0.13.1"
    hooks:
      - id: curlylint
        files: '^(.+)/templates/(.+)\.(html|jinja|twig)$'
  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: ruby-validate
        files: Dangerfile
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: markdownlint
        args: ["-r", "~MD013"]
        exclude: "CHANGELOG.md"
