"""
    Nomad Broker

    Nomad payment provider aggregation, including make payments, and customs declaration for orders and etc.  # noqa: E501

    The version of the OpenAPI document: 1.7.0
    Contact: ben.song@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_broker_cli
from nomad_broker_cli.model.payment_product_req import PaymentProductReq


class TestPaymentProductReq(unittest.TestCase):
    """PaymentProductReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentProductReq(self):
        """Test PaymentProductReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentProductReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
