[tool.poetry]
name = "asyncio-redis-rate-limit"
description = "Rate limiter for async functions using Redis as a backend"
version = "0.1.0"
license = "MIT"
readme = "README.md"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

repository = "https://github.com/wemake-services/aio-redis-rate-limit"

keywords = [
  "asyncio",
  "trio",
  "curio",
  "rate-limiter",
  "redis",
  "redis-py",
  "anyio",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.7"

redis = ">=4.3"
typing-extensions = ">=3.10"

[tool.poetry.dev-dependencies]
mypy = "^0.961"
types-redis = "^4.3.1"

# TODO: return after GitHub Actions is fixed
# wemake-python-styleguide = "^0.16"
# flake8-pytest-style = "^1.6"
doc8 = "^0.11"
nitpick = "^0.32"

safety = "^1.10"

pytest = "^7.1"
pytest-cov = "^3.0"
pytest-randomly = "^3.12"
pytest-asyncio = "^0.18"
pytest-freezegun = "^0.4"
pytest-repeat = "^0.9"
types-mock = "^4.0.15"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"
