[tool.poetry]
name = "falconcv"
version = "1.0.1"
description = ""
authors = ["Henry Ruiz <henry.ruiz@tamu.edu>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
rich = "^12.4.4"
tensorflow = "^2.9.1"
pandas = "^1.4.2"
matplotlib = "^3.5.2"
seaborn = "^0.11.2"
lxml = "^4.9.0"
Pillow = "^9.1.1"
GitPython = "^3.1.27"
validators = "^0.20.0"
requests = "^2.27.1"
alive-progress = "^2.4.1"
bs4 = "^0.0.1"
pydantic = "^1.9.1"
Mako = "^1.2.0"
tflite-support = "^0.4.1"
dask = {extras = ["dataframe"], version = "^2022.6.0"}
boto3 = "^1.24.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.3.0"
python-dotenv = "^0.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
