[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example_package_calculator"
version = "0.0.2"
authors = [
  { name="Andrius", email="osipovas.andrius@gmail.com" },
]
description = "A simple calclualtor"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]