[tool.poetry]
name = "colang"
version = "0.0.1"
description = "Clean, intuitive, and powerful modeling language for Conversational AI."
authors = ["Razvan Dinu <razvan@colang.ai>"]

[tool.poetry.dependencies]
requests = "^2.24.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
