name: datatoolbox
dependencies:
- appdirs
- pandas>=1.1
- regex
- numpy
- gitpython
- openscm-units
- pint>=0.11
- pycountry
- fuzzywuzzy
- tqdm
- matplotlib
- openpyxl
- pyam
- networkx>=2.4
- xarray
- pint-xarray
- deprecated
- beautifulsoup4
- itsdangerous
- ratelimit
- pytest
- black
- pylint
- pip
- pip:
  - hdx-python-country
  - -e .
