"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class TranslateStringRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class ArgsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> global___TranslateArgValue: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[global___TranslateArgValue] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    MODULE_INDEX_FIELD_NUMBER: builtins.int
    MESSAGE_INDEX_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    module_index: builtins.int
    message_index: builtins.int
    @property
    def args(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___TranslateArgValue]: ...
    def __init__(self,
        *,
        module_index: builtins.int = ...,
        message_index: builtins.int = ...,
        args: typing.Optional[typing.Mapping[typing.Text, global___TranslateArgValue]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","message_index",b"message_index","module_index",b"module_index"]) -> None: ...
global___TranslateStringRequest = TranslateStringRequest

class TranslateArgValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STR_FIELD_NUMBER: builtins.int
    NUMBER_FIELD_NUMBER: builtins.int
    str: typing.Text
    number: builtins.float
    def __init__(self,
        *,
        str: typing.Text = ...,
        number: builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["number",b"number","str",b"str","value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["number",b"number","str",b"str","value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value",b"value"]) -> typing.Optional[typing_extensions.Literal["str","number"]]: ...
global___TranslateArgValue = TranslateArgValue

class FormatTimespanRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Context:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ContextEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[FormatTimespanRequest._Context.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PRECISE: FormatTimespanRequest._Context.ValueType  # 0
        ANSWER_BUTTONS: FormatTimespanRequest._Context.ValueType  # 1
        INTERVALS: FormatTimespanRequest._Context.ValueType  # 2
    class Context(_Context, metaclass=_ContextEnumTypeWrapper):
        pass

    PRECISE: FormatTimespanRequest.Context.ValueType  # 0
    ANSWER_BUTTONS: FormatTimespanRequest.Context.ValueType  # 1
    INTERVALS: FormatTimespanRequest.Context.ValueType  # 2

    SECONDS_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    seconds: builtins.float
    context: global___FormatTimespanRequest.Context.ValueType
    def __init__(self,
        *,
        seconds: builtins.float = ...,
        context: global___FormatTimespanRequest.Context.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["context",b"context","seconds",b"seconds"]) -> None: ...
global___FormatTimespanRequest = FormatTimespanRequest

class I18nResourcesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MODULES_FIELD_NUMBER: builtins.int
    @property
    def modules(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        modules: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["modules",b"modules"]) -> None: ...
global___I18nResourcesRequest = I18nResourcesRequest
