[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mwparallelparserfromgary"
version = "1.0.0"
description = "MediaWiki parallel parser"
readme = "README.md"
authors = [{ name = "Marcin Garnowski", email = "gtrawirr@gmail.com" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["mediawiki", "parser", "parallel"]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/Trawirr/mwparallelparserfromgary"