
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-26T02:48:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5def7f0f470cafc07dc8b13ea633dbaa2a22192",
 "version": "0.10.dev2226"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
