class General:
    DATABASE = 'sofa_score'
    DECIMAL_FORMAT = '{: .2f}'


class Keys:
    EVENT_ID = 'event_id'
    START_TIME = 'start_time'
    ROUND = 'round'
    TOUR_ID = 'tour_id'
    TOUR_NAME = 'tour_name'
    TEAM_ID = 'team_id'
    TEAM_NAME = 'team_name'
    SEASON = 'season'
    SEASON_LEVEL = 'season_level'
    HOME_TEAM_ID = 'home_team_id'
    AWAY_TEAM_ID = 'away_team_id'
    HOME_TEAM_RANK = 'home_team_rank'
    AWAY_TEAM_RANK = 'away_team_rank'
    FAVORITE = 'favorite'
    UNDERDOG = 'underdog'
    EQUAL = 'equal'
    ID = 'id'
    NAME = 'name'
    RANK = 'rank'
    TOUR = 'tour'
    IN_PERCENT = 'in_percent'
    PRESSURE_LEVEL = 'pressure_level'
    STATE = 'state'
    DATA = 'data'
    RIVAL_RANK = 'rival_rank'
    GAME_OBJECT = 'game_object'
    TOTAL = 'total'
    WINNER_CODE = 'winner_code'
    POINTS = 'points'
    PSYCHOLOGY = 'psychology'
    FLOW = 'flow'
    RESULT = 'result'
    BALANCE = 'balance'
    UPDATE_RATING = 'update_rating'
    COME_BACK_POSITIVE = 'come_back_positive'
    COME_BACK_NEGATIVE = 'come_back_negative'
    GET_THE_LEAD_POSITIVE = 'get_the_lead_positive'
    GET_THE_LEAD_NEGATIVE = 'get_the_lead_negative'
    COME_BACK_TO_THE_GAME_POSITIVE = 'come_back_to_game_positive'
    COME_BACK_TO_THE_GAME_NEGATIVE = 'come_back_to_game_negative'
    DOUBLE_LEAD_POSITIVE = 'double_lead_positive'
    DOUBLE_LEAD_NEGATIVE = 'double_lead_negative'
    SIGNIFICANCE_HOME = 'significance_home'
    SIGNIFICANCE_AWAY = 'significance_away'
    COME_BACK_FROM_LOSING_POSITION = 'come_back_from_losing_position'
    LOST_THE_LEAD = 'lost_the_lead'
    DOUBLE_LEAD = 'double_lead'
    SECTION_RESULT = 'section_result'
    TOTAL_RATING = 'total_rating'
    LAST_5_GAMES = 'last_5_games'
    ALL_SEASON = 'all_season'
    ACHIEVED_POINTS = 'achieved_points'
    POTENTIAL_POINTS = 'potential_points'
    WIN = 'win'
    DREW = 'drew'
    LOST = 'lost'
    TOTAL_GAMES = 'total_games'
    TOTAL_CASES = 'total_cases'
    CASES = 'cases'


class Tables:
    EVENTS_DATA = 'events_data'
    EVENTS_PRESSURE_DATA = 'events_pressure'


class Columns:
    PRESSURE = 'rank', 'against rank', 'count', 'current_result', 'expected', 'balance'
