[tool.poetry]
name = "vinca"
version = "2.4.4"
description = "Spaced Repetition CLI"
authors = ["Oscar Laird <olaird25@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/oscarlaird/vinca-SRS"

[tool.poetry.dependencies]
python = "^3.8"
fire = "^0.4.0"
prompt-toolkit = "^3.0.29"
rich = "^12.4.1"

[tool.poetry.scripts]
vinca = "vinca:run"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
