[build-system]
requires = [
    "setuptools>=42",
    "scikit-build>=0.13.0",
    "cmake",
    "ninja; platform_system!='Windows'",
    "oldest-supported-numpy",
    "rapidfuzz_capi==1.0.5"
]
build-backend = "setuptools.build_meta"
