from typing import Optional, List


class Markdown:
    def __init__(
        self,
        plugins: Optional[List[str]] = ...
    ) -> None: ...
    def convert(self, text: str) -> str: ...
    def convert_file(self, filename: str) -> str: ...
    def __call__(self, text: str) -> str: ...


def create_markdown(plugins: Optional[List[str]] = ...) -> Markdown: ...
def convert(text: str) -> str: ...
def convert_file(filename: str) -> str: ...
