[project]
name = "doubanlib"
version = "0.0.9"
authors = [
  { name="xhboke", email="2361903575@qq.com" },
]
description = "An api tool for DouBan movie"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"