codecov:
  ci:
    - github.com
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
   
comment:
  behavior: default
  layout: "reach, diff, flags, files"
  require_base: no
  require_changes: false
  require_head: no
  
coverage:
  status:
    patch:
      default:
        informational: true
        only_pulls: false
        target: auto
        if_ci_failed: error
    project:
      default:
        informational: true
        only_pulls: false
        target: auto
        if_ci_failed: error
      cxxcimod:
        informational: true
        only_pulls: false
        target: auto
        if_ci_failed: error
        flags:
          - cxxcimod
      cimod:
        informational: true
        only_pulls: false
        target: auto
        if_ci_failed: error
        flags:
          - cimod
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes
      
flag_management:
  default_rules: 
    carryforward: true
flags:
  cxxcimod:
    paths: 
      - src
    carryforward: true
  cimod:
    paths: 
      - cimod
    carryforward: true

ignore:
  - "test"
 
github_checks:
  annotations: true
