# Generated by Django 4.0.5 on 2022-06-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'swappable': 'CART_PRODUCT',
            },
        ),
    ]
