# Generated by Django 4.0.5 on 2022-06-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
