[tool.poetry]
name = "spraymistf638"
version = "0.1.7"
description = ""
authors = ["Pawel Kowalik <github-pub@paulonet.eu>"]
license = "Apache-2.0"
repository = "https://github.com/paulokow/Spray-Mist-F638-driver-bluepy"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: System :: Hardware :: Hardware Drivers"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.2"
bluepy = ">=1.3.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
pytest-sugar = "^0.9.4"
tox = "^3.24.4"
tox-pyenv = "^1.1.0"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
