[tool.poetry]
name = "mirrorlib"
version = "0.1.0"
description = "A generic specification for mirroring data"
readme = "README.md"
authors = ["wkrettek <50168688+wkrettek@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
