[tool.poetry]
name = "dapp-api"
version = "0.0.2"
description = "Golden's Python wrapper for the dApp GraphQL API"
authors = ["aychang95"]

[tool.poetry.dependencies]
python = "~3.9"
wheel = "^0.36.2"
tqdm = "^4.63.1"
sgqlc = "^16.0"
requests = "^2.27.1"
web3 = {version="^5.28.0", optional = true}
jupyterlab = {version="^3.0.0", optional = true}
ipywidgets = {version="^7.6.3", optional = true}
pandas = {version="^1.4.1", optional = true}
numpy = {version="^1.22.3", optional = true}
mkdocs = {version="^1.3.0", optional = true}
mkdocs-material = {version="^8.2.9", optional = true}
mkdocstrings = {version="^0.18.1", optional = true}
mkdocs-jupyter = {version="^0.20.1", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
black = "^20.8b1"

[tool.poetry.extras]
docs = ["mkdocs-material", "mkdocstrings", "mkdocs-jupyter"]
web3 = ["web3"]
data-tools = ["jupyterlab", "ipywidgets", "pandas", "numpy"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
