[tool.poetry]
name = 'datastory'
version = '0.1.13'
description = ''
authors = ['nada developers <nada@nav.no>']

[tool.poetry.dependencies]
python = '^3.7'
requests = '^2.26.0'
ipython = '^7.30.1'

[tool.poetry.dev-dependencies]
pytest = '^5.2'

[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'
