[build-system]
requires = ['setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-fem<=2.8.0.7', 'dune-grid<=2.8.0.7', 'gmsh', 'dune-grid<=2.8.0.7']
build-backend = 'setuptools.build_meta'
