[tool.poetry]
name = "coshed-model"
version = "0.14.3"
description = ""
authors = ["doubleO8 <wb008@hdm-stuttgart.de>"]

[tool.poetry.dependencies]
python = "^3.6.2"
SQLAlchemy = "^1.4.2"
pendulum = "^2.1.2"
djali = "^0.2.0"
boto3 = "^1.18.21"
orjson = "^3.6.1"
coshed = "^0.11.3"
cryptography = ">=3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.5b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
