name: pip-install
on: ["push", "pull_request"]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-18.04

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Pip Install
      run: |
        python -m pip install --upgrade pip
        pip install ceres-raytracer