name: Tests
on: ["push", "pull_request"]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov==3.0.0
        pytest --cov-config=tests/.coveragerc --cov=crt tests/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        files: ./coverage.xml