[tool.poetry]
name = "pybiolib"
version = "1.0.1909"
description = "BioLib Python Client"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/biolib"
keywords = ["biolib"]
authors = [
    "biolib <hello@biolib.com>",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
packages = [
    { include = "biolib" },
]
include = [
    "README.md",
    "LICENSE",
    "pyppeteer",
]

[tool.poetry.scripts]
biolib = "biolib:call_cli"

[tool.poetry.dependencies]
requests = ">=2.25.1"
python = "^3.6"
aenum = "^2.2.3"
appdirs = "^1.4.3"
certifi = ">=2019.11.28"
ordered_set = "^4.0.1"
pyee = "^7.0.1"
tqdm = "^4.42.1"
typing_extensions = { version = "==3.10.0", python = "<3.8" }
typing_inspect = { version = "^0.5.0", python = "<3.8" }
websockets = ">=8.0"
pyyaml = ">=5.3.1"
docker = "==4.4.1"
nest_asyncio = ">= 1.4.0, < 1.5.2"
gunicorn = "==20.1.0"
flask = "==2.0.1"
flask-cors = "==3.0.10"
pycryptodome = "==3.9.9"
importlib-metadata = ">=1.6.1"
termcolor = "==1.1.0"
cryptography = ">= 3.1, < 36.0.2"
spython = ">=0.1.18"
pyjwt = "==2.3.0"

[tool.poetry.dev-dependencies]
mypy = "==0.910"
pylint = "==2.7.4"
pytest = "==6.2.4"
types-Flask = "==1.1.1"
types-PyYAML = "==5.4.3"
types-requests = "==2.25.0"
types-termcolor = "==0.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
