[tool.poetry]
name = "BlockFiRates"
version = "0.3.2"
description = "Scrape the latest APY rates for BlockFi Interest Accounts"
authors = ["P.G. Ó Slatara <pgoslatara@gmail.com>"]
keywords = ["crypto", "python3", "blockfi"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pgoslatara/blockfirates"
repository = "https://github.com/pgoslatara/blockfirates"
classifiers = [
    "Environment :: Console",
    "Framework :: Flake8",
    "Programming Language :: Python :: 3"
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"
cloudscraper = "^1.2.58"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.1.0", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"

[tool.poetry-dynamic-versioning]
bump = true
enable = true
style = "semver"
vcs = "git"
