- name: cortexA76cpu_tflite21
  version: 1.0
  category: cpu
  kernel_predictors:
    - conv-bn-relu
    - dwconv-bn-relu
    - fc
    - global-avgpool
    - hswish
    - relu
    - se
    - split
    - add
    - addrelu
    - maxpool
    - avgpool
    - bn
    - bnrelu
    - channelshuffle
    - concat
  download: https://github.com/microsoft/nn-Meter/releases/download/v1.0-data/cortexA76cpu_tflite21.zip

- name: adreno640gpu_tflite21
  version: 1.0
  category: gpu
  kernel_predictors:
    - conv-bn-relu
    - dwconv-bn-relu
    - hswish
    - relu
    - se
    - maxpool
    - avgpool
    - bn
    - bnrelu
    - concat
  download: https://github.com/microsoft/nn-Meter/releases/download/v1.0-data/adreno640gpu_tflite21.zip

- name: adreno630gpu_tflite21
  version: 1.0
  category: gpu
  kernel_predictors:
    - conv-bn-relu
    - dwconv-bn-relu
    - hswish
    - relu
    - se
    - maxpool
    - avgpool
    - bn
    - bnrelu
    - concat
  download: https://github.com/microsoft/nn-Meter/releases/download/v1.0-data/adreno630gpu_tflite21.zip

- name: myriadvpu_openvino2019r2
  version: 1.0
  category: vpu
  kernel_predictors:
    - conv-bn-relu
    - dwconv-bn-relu
    - fc
    - hswish
    - relu
    - se
    - addrelu
    - maxpool
    - avgpool
    - bn
    - bnrelu
    - channelshuffle
  download: https://github.com/microsoft/nn-Meter/releases/download/v1.0-data/myriadvpu_openvino2019r2.zip