[tool.yapf]
based_on_style = "pep8"
no_spaces_around_selected_binary_operators = true
spaces_around_power_operator = false

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
