version: "2"
services:
  plone:
    image: plone:5
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.coremetadata
    environment:
      ADDONS: "eea.coremetadata[test]"
      DEVELOP: "src/eea.coremetadata"
