name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - mamba
  - pydata-sphinx-theme
  - empack
  - pip

  - pip:
      - jupyterlite
      - jupyterlite-sphinx
      - jupyterlite-xeus-python==0.4.2
