[project]
name = "creart"
version = "0.2.1"
description = "a universal, extensible class instantiation helper"
authors = [
    { name = "GreyElaina", email = "GreyElaina@outlook.com" },
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[project.optional-dependencies]

[tool.pdm.dev-dependencies]
dev = [
    "black>=22.3.0",
    "isort>=5.10.1",
]

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
