[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "parse_log"
requires-python = ">=3.7"
keywords = ["log", "tail", "parse", "files"]
readme = "README.md"
description = "Rust tail implementation"
license = {file = "license-mit"}
maintainers = [
  {name = "killown", email = "developerorprogrammer@gmail.com"}
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[project.urls]
homepage = "https://github.com/killown/parse-log"
repository = "https://github.com"
