
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-23T15:40:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0bb972bd615381c3d7f1a28382e0df7130acd06f",
 "version": "1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
