[tool.poetry]
name = "internal-match-hooks"
version = "0.1.0"
description = "A replaCy match hoold lib"
authors = [
    "Sam Havens <sam.havens@writer.com>",
    "Manhal Daaboul <manhal@writer.com>"
]
license = "Proprietary"
readme = "README.md"
homepage = "https://github.writer.ai/nlp/internal-match-hooks"
repository = "https://github.writer.ai/nlp/internal-match-hooks"

[[tool.poetry.source]]
name = "artifactory"
url = "https://writer.jfrog.io/artifactory/api/pypi/pypi-virt/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.3.0/en_core_web_sm-3.3.0.tar.gz" }
pytest = "^5.2"
black = "^20.8b1"
mypy = "^0.782"
replacy = "^3.6.1"
spacy = "^3.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
