[tool.poetry]
name = "fdn"
version = "0.1.0"
description = ""
authors = ["hobbymarks"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = ">=8.0"
emoji = ">=1.7.0"
SQLAlchemy = ">=1.4.35"
pandas = "^1.4.2"
wcwidth = "^0.2.5"
colorama = "^0.4.4"
Unidecode = "^1.3.4"
cryptography = "^37.0.2"
nltk = "^3.7"
twine = "^4.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
