"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import dmss_api
from dmss_api.model.remove_by_path_request import RemoveByPathRequest


class TestRemoveByPathRequest(unittest.TestCase):
    """RemoveByPathRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoveByPathRequest(self):
        """Test RemoveByPathRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoveByPathRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
