[tool.poetry]
name = "dooit"
version = "0.2.0"
description = "A TUI todo manager"
authors = ["kraanzu <kraanzu@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
textual = "^0.1.17"
pyperclip = "^1.8.2"
PyYAML = "^6.0"
poetry = "^1.1.13"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
pre-commit = "^2.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dooit = 'dooit.__init__:main'
