[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "study-cli"
version = "0.0.1"
authors = [
  { name="Example Author", email="fawzisal001@gmail.com" },
]
description = "command line flash cards"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/fawzisal/study-cli"
"Bug Tracker" = "https://github.com/fawzisal/study-cli/issues"
