
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-28T09:50:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "19b2665bb1acc9a2be118c497178ba93f0bdb418",
 "version": "0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
