from edgeiq import constants as constants

class JsonFile:
    def __init__(self, path) -> None: ...
    @property
    def contents(self): ...
    def exists(self): ...
    def load(self): ...

class AppFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def analytics_cfg(self): ...
    @property
    def model_id(self): ...

class ProjectFile(JsonFile):
    def __init__(self) -> None: ...
    @property
    def project_id(self): ...

def load_app_config() -> None: ...
def load_project_config() -> None: ...
