from edgeiq import constants as constants, edge_tools as edge_tools, processing as processing
from edgeiq.base_service import BaseService as BaseService

class SemanticSegmentationResults:
    def __init__(self, class_map, duration, image) -> None: ...
    @property
    def duration(self): ...
    @property
    def class_map(self): ...
    @property
    def image(self): ...

class SemanticSegmentation(BaseService):
    def __init__(self, model_id) -> None: ...
    def segment_image(self, image): ...
    def build_image_mask(self, class_map): ...
    def build_legend(self): ...
    def build_object_map(self, class_map, class_list): ...
