
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-28T03:45:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e080b0ed053c89f0098ecb0a4bfa5e50fc77d0c",
 "version": "1.16.0.post.dev839"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
