
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-23T21:29:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "15fb29d710df85ccb679a25e5a32b5ff78f49067",
 "version": "0.2.10.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
