[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "soxaitool"
version = "0.0.5"
authors = [
  { name="Jiabin Wang", email="wjbthu@gmail.com" },
]
description = "A new tool for soxai research"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://soxai.co.jp/"
"Bug Tracker" = "https://soxai.co.jp/"