
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-25T08:36:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "aca4e57d39799f1d75246424ba9c47153fb966da",
 "version": "3.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
