name: py-cordex-notebooks
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - matplotlib-base
  - numpy
  - pooch
  - regionmask
  - setuptools
  - xarray
  - cftime
  - netCDF4
  - xesmf
  - cdo==1.9.9 # python-cdo fails with cdo2
  - python-cdo
  - pip:
    - git+https://github.com/euro-cordex/py-cordex.git  # latest py-cordex version
