[tool.poetry]
name = "json-position-mapper"
version = "0.1.0"
description = "Map file-based JSON inputs from the file keys to their locations in the original file"
authors = ["Adam Peacock <apeacock@atlantistech.com>", "Adam Peacock <adam@thepeacock.net>"]
license = "MIT"
packages = [
    { include = "json_mapper" },
]

include = [
    "LICENSE"
]

readme = "Readme.md"
homepage = "https://github.com/atlantistechnology/json-position-mapper"
repository = "https://github.com/atlantistechnology/json-position-mapper"

classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

[tool.poetry.dependencies]
python = ">=3.7,<4"
json-stream = ">=1.3.0"

[tool.poetry.dev-dependencies]
rope = "^1.1.1"
mypy = "^0.961"
black = "^22.3.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[[tool.mypy.overrides]]
module = ["json_stream", "json_stream.base"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
