
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-20T18:14:14-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2cad6f4385f8b115c7ec3f9feac637d7bf0f1d33",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
