
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-22T12:28:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "111eebe09d292d60973108812d70183caed91bd5",
 "version": "1.42.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
