
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-21T19:48:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3ad2143562013b72a57b8a737e47e0769e80c60",
 "version": "0.2.8.post0.dev22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
