
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-26T02:48:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "66c8f4a8999f9e2e1a7e10f30e7648a3a5b427c2",
 "version": "0.4.dev2226"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
