agent_name: my_first_aea
author: open_aea
version: 0.1.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmaQRtL9NESStgoojt3oUkp8o1Xb9ZyhCmqhVBijYiBc7U
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:QmektTWmXcjThQd8md8nSYgLapR3Gks3n3WEzwAWQFgc4z
contracts: []
protocols:
- fetchai/default:1.0.0:QmYNdsSrdKRvJGKjAbREuvkjGXgnanDjxCBS8CfJb9fzr1
- fetchai/state_update:1.0.0:QmZ9dxrmQTZCpA5VuamxBticK4CUZAfPsraTodksvmcqHx
- open_aea/signing:1.0.0:QmRL1Qt5TEzbw6xRn3grz1fe22uM761AXL8UQ8QvGmQn8K
skills:
- fetchai/echo:0.19.0:QmQxMpYwxRNCNzEqWaPmNXFTWgu4Xmz89ZjTp2TQu3wbPM
default_connection: fetchai/stub:0.21.0
default_ledger: ethereum
required_ledgers:
- ethereum
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-ethereum:
    version: <2.0.0,>=1.0.0
