[tool.poetry]
name = "enpyre"
version = "0.0.6"
description = "A Python game engine for the browser"
authors = ["Lucas Amoedo <lucas.advc@gmail.com>", "Vitor Nere <vitor.nere@hotmail.com>"]
license = "MPL-2.0"
readme = "README.md"
homepage = "https://github.com/Enpyre/engine"
repository = "https://github.com/Enpyre/engine"
keywords = ["game", "engine", "python", "browser"]
packages = [{include = "enpyre", from = "src"}]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Other Environment",
  "Environment :: Web Environment",
  "Intended Audience :: Education",
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
  "Topic :: Education",
  "Topic :: Games/Entertainment"
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
aiohttp = "^3.8.1"
aiohttp_cors = "^0.7.0"
watchfiles = "^0.14.1"
mypy = "^0.961"
flake8 = "^4.0.1"
pre-commit = "^2.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
