[tool.poetry]
name = "utrello"
version = "0.8.0"
description = ""
authors = ["Davi Koscianski Vidal <davividal@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.0"
pandas = "^1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
prospector = "^1.7.7"
pytest-cov = "^3.0.0"

[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
utrello = "utrello:main"

[tool.semantic_release]
version_variable = [
    "src/utrello/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "master"
upload_to_pypi = true
build_command = "pip install poetry && poetry build"