[tool.poetry]
name = "pybotx-smartapp-smart-logger"
version = "0.2.6"
description = ""
authors = ["Arseniy Zhiltsov <arseniy.zhiltsov@ccsteam.ru>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.11"

pybotx = ">=0.42.0,<0.45.0"
pybotx-smart-logger = ">=0.6.7,<0.8.0"
pybotx-smartapp-rpc = ">=0.5.0,<0.6.0"

[tool.poetry.dev-dependencies]
black = "22.3.0"
isort = "^4.3"
autoflake = "^1.4"
mypy = "0.910"
wemake-python-styleguide = "0.16.1"

pytest = "^7.0.1"
pytest-asyncio = "^0.18.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
