
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-22T10:25:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "09eabbc861433ce0e8c025a711492ee1bfc065f4",
 "version": "0.15.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
