[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "impact-stack-auth-wsgi-middleware"
version = "0.2.0"
dependencies = [
    "itsdangerous",
    "redis<4.1",
    "werkzeug>=2.1",
]
authors = [
  {name = "Roman Zimmermann", email = "roman@more-onion.com"},
]
readme = "README.md"

[tool.black]
line-length = 100

[tool.coverage.run]
source = ["impact_stack"]
relative_files = true

[tool.coverage.report]
fail_under = 90

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true

[tool.pydocstyle]
convention = "google"

[tool.pylint.basic]
good-names = ["db"]

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "100"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=term --cov-report=xml --junitxml=pytest-junit.xml"
python_classes = [
  "*Test",
  "Test*",
]

[tool.setuptools]
packages = ["impact_stack.auth_wsgi_middleware"]
