[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=fastchain"
testpaths = [
    "tests"
]

[tool.mypy]
mypy_path = "fastchain"
check_untyped_defs = true
