[project]
name = "bed-reader"
readme = "README.md"

[build-system]
requires = ["maturin==0.12.5"]
build-backend = "maturin"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.black]
line-length = 88

[tool.maturin]
# https://github.com/PyO3/pyo3/discussions/2271
cargo-extra-args = "--features extension-module"

[build]
# https://nnethercote.github.io/perf-book/compile-times.html
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
