[tool.poetry]
name = "b4022"
version = "0.1.0"
description = ""
authors = ["Aisten <gvilkson@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.0"
Django = "^4.0.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^8.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
