[tool.poetry]
name = "ou-sphinx-a11y"
version = "0.1.1"
description = ""
authors = ["Mark Hall <mark.hall@open.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
sphinx = ">=4.2.0 <6.0.0"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."sphinx.builders"]
"a11ycheck" = "ou_sphinx_a11y"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
