[tool.poetry]
name = "motion_planning_scenes"
version = "0.1.19"
description = "Generic motion planning scenes, including goals and obstacles."
authors = ["Max <m.spahn@tudelft.nl>"]
packages = [
  { include = "MotionPlanningSceneHelpers" },
  { include = "MotionPlanningGoal" },
  { include = "MotionPlanningEnv" },
]
  

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19.0"
casadi = "3.5.6.pre2"
PyYAML = "^6.0"
geomdl = "^5.3.1"
pytest = "^6.2.5"
pyquaternion = "^0.9.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
