# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Running tests

on: push
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install eigen
      run: |
        wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz 
        tar xzf eigen-3.4.0.tar.gz

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11

        sudo apt update
        sudo apt -y install libglu1

    - name: Install package
      run: |
        export BOLA_EIGEN_DIR=./eigen-3.4.0/
        pip install .[test]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics bola
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics bola
    - name: Test with pytest
      run: |
        pytest
