[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tccl"
version = "0.0.1"
authors = [
  { name="Luca Wehrstedt", email="luca.wehrstedt@gmail.com" },
]
description = "TensorPipe Collective Communication Library"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/fairinternal/tccl"
