[tool.poetry]
name = "lacecore"
version = "3.0.0a0"
description = "Polygonal meshes optimized for cloud computation"
authors = ["Paul Melnikow <github@paulmelnikow.com>", "Metabolize, Minnow Software, Body Labs, and other contributors"]
license = "BSD-2-Clause"
include = ["CHANGELOG.md"]
exclude = ["**/test_*.py"]
homepage = "https://github.com/lace/lacecore"
repository = "https://github.com/lace/lacecore"
documentation = "https://lacecore.readthedocs.io/en/stable/"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Manufacturing",
    "Topic :: Artistic Software",
    "Topic :: Multimedia :: Graphics :: 3D Modeling",
    "Topic :: Scientific/Engineering :: Visualization",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.7,<4"
numpy = "<1.19.0"
ounce = ">=1.1.0,<2.0"
polliwog = ">=3.0.0a3"
# polliwog = {git = "https://github.com/lace/polliwog.git", branch = "slice-mapping"}
tinymetabobjloader = {version = "2.0.0a0", optional = true}
vg = ">=2.0.0"

[tool.poetry.extras]
obj = ["tinymetabobjloader"]

[tool.poetry.dev-dependencies]
black = "21.6b0"
click = "8.0.1"
coverage = "5.5"
executor = "23.2"
flake8 = "3.9.2"
flake8-import-order = "0.18.1"
myst-parser = "0.15.1"
pytest = "6.2.4"
pytest-cov = "2.12.1"
Sphinx = "4.1.0"
sphinxcontrib-apidoc = "0.3.0"


[build-system]
# Lint requires setuptools.
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.report]
fail_under = 100.0
omit = ["**/test_*.py"]
