[tool.poetry]
name = "hellebore-otcstreaming"
version = "0.1.1"
description = "API Wrapper for OTCStreaming."
authors = ["Benjamin Denise <bdenise@helleboretech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
tox = "^3.25.0"

[tool.poetry.extras]
test = ["tox", "pytest"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
