[project]
name = "datazimmer"
dynamic = ["version", "description"]
authors = [{name = "Social Science Computing Unit Budapest", email = "borza.endre@krtk.hu"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.8"
scripts = {datazimmer = "datazimmer:app", dz = "datazimmer:app"}
dependencies = [
    "flit",
    "twisted",
    "wheel>=0.37.0",
    "pip>=22.0.0",
    "setuptools>=60.0.0",
    "requests",
    "dvc[s3,ssh]",
    "paramiko",
    "parquetranger>=0.2.3",
    "colassigner>=0.2.2",
    "pyyaml",
    "structlog",
    "black>=21.5b0",
    "isort",
    "flake8",
    "sqlalchemy",
    "toml",
    "pyinstrument",
    "tqdm",
    "typer",
    "pandas<1.4.0",
    "cookiecutter",
    "sqlmermaid",
    "cron-descriptor",
    "metazimmer"
]

[project.optional-dependencies]
full = ["psycopg2"]
explorer = [
    "pandas_profiling", 
    "jupyter-book==0.12.2", 
    "sphinxcontrib-mermaid", 
    "beautifulsoup4",
    "html5lib"
]
test = ["branthebuilder"]
doc = [
    "sphinx",
    "pandoc",
    "graphviz",
    "sphinx-automodapi",
    "sphinx-rtd-theme",
    "myst-parser",
    "pygments",
    "jupyter",
    "toml"
]

[project.urls]
Homepage = "https://github.com/sscu-budapest/datazimmer"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.branb]
line-length = 88
[tool.pytest.ini_options]
addopts = "-s"
