"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.search_indexed_objects_request_all_of_cassandra_params import SearchIndexedObjectsRequestAllOfCassandraParams


class TestSearchIndexedObjectsRequestAllOfCassandraParams(unittest.TestCase):
    """SearchIndexedObjectsRequestAllOfCassandraParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchIndexedObjectsRequestAllOfCassandraParams(self):
        """Test SearchIndexedObjectsRequestAllOfCassandraParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchIndexedObjectsRequestAllOfCassandraParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
