"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cohesity_sdk
from cohesity_sdk.api.identity_provider import IdentityProviderApi  # noqa: E501


class TestIdentityProviderApi(unittest.TestCase):
    """IdentityProviderApi unit test stubs"""

    def setUp(self):
        self.api = IdentityProviderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_identity_provider(self):
        """Test case for create_identity_provider

        Configure identity provider  # noqa: E501
        """
        pass

    def test_delete_identity_provider(self):
        """Test case for delete_identity_provider

        Delete identity provider  # noqa: E501
        """
        pass

    def test_get_identity_providers(self):
        """Test case for get_identity_providers

        Get identity providers  # noqa: E501
        """
        pass

    def test_idps_login(self):
        """Test case for idps_login

        Login to cluster using idp  # noqa: E501
        """
        pass

    def test_update_identity_provider(self):
        """Test case for update_identity_provider

        Update identity provider  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
