"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.create_tdm_task_request_all_of import CreateTdmTaskRequestAllOf
from cohesity_sdk.cluster.model.tdm_clone_task_request_params import TdmCloneTaskRequestParams
from cohesity_sdk.cluster.model.tdm_refresh_task_request_params import TdmRefreshTaskRequestParams
from cohesity_sdk.cluster.model.tdm_snapshot_task_params import TdmSnapshotTaskParams
from cohesity_sdk.cluster.model.tdm_teardown_task_request_params import TdmTeardownTaskRequestParams
globals()['CreateTdmTaskRequestAllOf'] = CreateTdmTaskRequestAllOf
globals()['TdmCloneTaskRequestParams'] = TdmCloneTaskRequestParams
globals()['TdmRefreshTaskRequestParams'] = TdmRefreshTaskRequestParams
globals()['TdmSnapshotTaskParams'] = TdmSnapshotTaskParams
globals()['TdmTeardownTaskRequestParams'] = TdmTeardownTaskRequestParams
from cohesity_sdk.model.create_tdm_task_request61e3c2936d0d49dd_a9562e7072319f48 import CreateTdmTaskRequest61e3c2936d0d49ddA9562e7072319f48


class TestCreateTdmTaskRequest61e3c2936d0d49ddA9562e7072319f48(unittest.TestCase):
    """CreateTdmTaskRequest61e3c2936d0d49ddA9562e7072319f48 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTdmTaskRequest61e3c2936d0d49ddA9562e7072319f48(self):
        """Test CreateTdmTaskRequest61e3c2936d0d49ddA9562e7072319f48"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTdmTaskRequest61e3c2936d0d49ddA9562e7072319f48()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
