"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.elastifile_object_protection_request_params import ElastifileObjectProtectionRequestParams
from cohesity_sdk.cluster.model.flashblade_object_protection_request_params import FlashbladeObjectProtectionRequestParams
from cohesity_sdk.cluster.model.generic_nas_object_protection_request_params import GenericNasObjectProtectionRequestParams
from cohesity_sdk.cluster.model.gpfs_object_protection_request_params import GpfsObjectProtectionRequestParams
from cohesity_sdk.cluster.model.isilon_object_protection_request_params import IsilonObjectProtectionRequestParams
from cohesity_sdk.cluster.model.mssql_object_protection_request_params import MssqlObjectProtectionRequestParams
from cohesity_sdk.cluster.model.netapp_object_protection_request_params import NetappObjectProtectionRequestParams
from cohesity_sdk.cluster.model.office365_user_mailbox_object_protection_request_params import Office365UserMailboxObjectProtectionRequestParams
from cohesity_sdk.cluster.model.vmware_object_protection_request_params import VmwareObjectProtectionRequestParams
globals()['ElastifileObjectProtectionRequestParams'] = ElastifileObjectProtectionRequestParams
globals()['FlashbladeObjectProtectionRequestParams'] = FlashbladeObjectProtectionRequestParams
globals()['GenericNasObjectProtectionRequestParams'] = GenericNasObjectProtectionRequestParams
globals()['GpfsObjectProtectionRequestParams'] = GpfsObjectProtectionRequestParams
globals()['IsilonObjectProtectionRequestParams'] = IsilonObjectProtectionRequestParams
globals()['MssqlObjectProtectionRequestParams'] = MssqlObjectProtectionRequestParams
globals()['NetappObjectProtectionRequestParams'] = NetappObjectProtectionRequestParams
globals()['Office365UserMailboxObjectProtectionRequestParams'] = Office365UserMailboxObjectProtectionRequestParams
globals()['VmwareObjectProtectionRequestParams'] = VmwareObjectProtectionRequestParams
from cohesity_sdk.model.env_specific_object_protection_request_params import EnvSpecificObjectProtectionRequestParams


class TestEnvSpecificObjectProtectionRequestParams(unittest.TestCase):
    """EnvSpecificObjectProtectionRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvSpecificObjectProtectionRequestParams(self):
        """Test EnvSpecificObjectProtectionRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnvSpecificObjectProtectionRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
