"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cohesity_sdk
from cohesity_sdk.api.internal import InternalApi  # noqa: E501


class TestInternalApi(unittest.TestCase):
    """InternalApi unit test stubs"""

    def setUp(self):
        self.api = InternalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_refresh_bulletin_board(self):
        """Test case for refresh_bulletin_board

        Refresh bulletin board from Helios.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
