"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.protection_group_alerting_policy import ProtectionGroupAlertingPolicy
from cohesity_sdk.cluster.model.sla_rule import SlaRule
from cohesity_sdk.cluster.model.time_of_day import TimeOfDay
globals()['ProtectionGroupAlertingPolicy'] = ProtectionGroupAlertingPolicy
globals()['SlaRule'] = SlaRule
globals()['TimeOfDay'] = TimeOfDay
from cohesity_sdk.model.common_protection_group_request_params2384072a0e0849d28bd538044d7ffd40 import CommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40


class TestCommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40(unittest.TestCase):
    """CommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40(self):
        """Test CommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
