"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cohesity_sdk
from cohesity_sdk.api.protection_sources import ProtectionSourcesApi  # noqa: E501


class TestProtectionSourcesApi(unittest.TestCase):
    """ProtectionSourcesApi unit test stubs"""

    def setUp(self):
        self.api = ProtectionSourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_protection_source_registration(self):
        """Test case for delete_protection_source_registration

        Delete Protection Source Registration.  # noqa: E501
        """
        pass

    def test_get_protection_source_registration(self):
        """Test case for get_protection_source_registration

        Get a Protection Source registration.  # noqa: E501
        """
        pass

    def test_get_protection_sources(self):
        """Test case for get_protection_sources

        Get a List of Protection Sources.  # noqa: E501
        """
        pass

    def test_get_source_attribute_filters(self):
        """Test case for get_source_attribute_filters

        List attribute filters for a source.  # noqa: E501
        """
        pass

    def test_get_source_registrations(self):
        """Test case for get_source_registrations

        Get the list of Protection Source registrations.  # noqa: E501
        """
        pass

    def test_get_vdc_details(self):
        """Test case for get_vdc_details

        Get VDC Details.  # noqa: E501
        """
        pass

    def test_protection_source_by_id(self):
        """Test case for protection_source_by_id

        Get a Protection Sources.  # noqa: E501
        """
        pass

    def test_refresh_protection_source_by_id(self):
        """Test case for refresh_protection_source_by_id

        Refresh a Protection Source.  # noqa: E501
        """
        pass

    def test_register_protection_source(self):
        """Test case for register_protection_source

        Register a Protection Source.  # noqa: E501
        """
        pass

    def test_test_connection_protection_source(self):
        """Test case for test_connection_protection_source

        Test connection to a source.  # noqa: E501
        """
        pass

    def test_update_protection_source_registration(self):
        """Test case for update_protection_source_registration

        Update Protection Source registration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
