"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.recover_netapp_params import RecoverNetappParams
globals()['RecoverNetappParams'] = RecoverNetappParams
from cohesity_sdk.model.common_recovery_request_params728e9e8e_d3a3409e84ad_fc344fdac5ed_recover_netapp_params_wrapper_all_of import CommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverNetappParamsWrapperAllOf


class TestCommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverNetappParamsWrapperAllOf(unittest.TestCase):
    """CommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverNetappParamsWrapperAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverNetappParamsWrapperAllOf(self):
        """Test CommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverNetappParamsWrapperAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverNetappParamsWrapperAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
