"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_tdm_object_timeline_events_response_paramsb40f6965884b4986_a1bf70e3f7ac9929 import CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929
from cohesity_sdk.cluster.model.common_tdm_object_timeline_events_response_paramsb40f6965884b4986_a1bf70e3f7ac9929_tdm_snapshot_wrapper_all_of import CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapperAllOf
from cohesity_sdk.cluster.model.tdm_snapshot import TdmSnapshot
globals()['CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929'] = CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929
globals()['CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapperAllOf'] = CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapperAllOf
globals()['TdmSnapshot'] = TdmSnapshot
from cohesity_sdk.model.common_tdm_object_timeline_events_response_paramsb40f6965884b4986_a1bf70e3f7ac9929_tdm_snapshot_wrapper import CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapper


class TestCommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapper(unittest.TestCase):
    """CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapper(self):
        """Test CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonTdmObjectTimelineEventsResponseParamsb40f6965884b4986A1bf70e3f7ac9929TdmSnapshotWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
