"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cohesity_sdk
from cohesity_sdk.api.connectors import ConnectorsApi  # noqa: E501


class TestConnectorsApi(unittest.TestCase):
    """ConnectorsApi unit test stubs"""

    def setUp(self):
        self.api = ConnectorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_rigel_connector(self):
        """Test case for create_rigel_connector

        Create a Rigel connector on the cluster.  # noqa: E501
        """
        pass

    def test_delete_bifrost_connector(self):
        """Test case for delete_bifrost_connector

        Delete a Bifrost connector.  # noqa: E501
        """
        pass

    def test_delete_rigel_connector(self):
        """Test case for delete_rigel_connector

        Delete a Rigel connector.  # noqa: E501
        """
        pass

    def test_get_bifrost_connector(self):
        """Test case for get_bifrost_connector

        Get Bifrost connectors on the cluster.  # noqa: E501
        """
        pass

    def test_get_bifrost_connector_by_id(self):
        """Test case for get_bifrost_connector_by_id

        Get a Bifrost connector by the id.  # noqa: E501
        """
        pass

    def test_get_rigel_connector(self):
        """Test case for get_rigel_connector

        Get Rigel connectors on the cluster.  # noqa: E501
        """
        pass

    def test_get_rigel_connector_by_id(self):
        """Test case for get_rigel_connector_by_id

        Get a Rigel connector by the id.  # noqa: E501
        """
        pass

    def test_update_bifrost_connector(self):
        """Test case for update_bifrost_connector

        Update a Bifrost connector.  # noqa: E501
        """
        pass

    def test_update_rigel_connector(self):
        """Test case for update_rigel_connector

        Update a Rigel connector.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
