"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_object_protect_params import CommonObjectProtectParams
from cohesity_sdk.cluster.model.elastifile_object_protection_update_request_params import ElastifileObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.env_specific_object_protection_update_request_params import EnvSpecificObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.flashblade_object_protection_update_request_params import FlashbladeObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.generic_nas_object_protection_update_request_params import GenericNasObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.gpfs_object_protection_update_request_params import GpfsObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.isilon_object_protection_update_request_params import IsilonObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.mssql_object_protection_update_request_params import MssqlObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.netapp_object_protection_update_request_params import NetappObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.office365_user_mailbox_object_protection_update_request_params import Office365UserMailboxObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.sla_rule import SlaRule
from cohesity_sdk.cluster.model.time_of_day import TimeOfDay
from cohesity_sdk.cluster.model.vmware_object_protection_update_request_params import VmwareObjectProtectionUpdateRequestParams
globals()['CommonObjectProtectParams'] = CommonObjectProtectParams
globals()['ElastifileObjectProtectionUpdateRequestParams'] = ElastifileObjectProtectionUpdateRequestParams
globals()['EnvSpecificObjectProtectionUpdateRequestParams'] = EnvSpecificObjectProtectionUpdateRequestParams
globals()['FlashbladeObjectProtectionUpdateRequestParams'] = FlashbladeObjectProtectionUpdateRequestParams
globals()['GenericNasObjectProtectionUpdateRequestParams'] = GenericNasObjectProtectionUpdateRequestParams
globals()['GpfsObjectProtectionUpdateRequestParams'] = GpfsObjectProtectionUpdateRequestParams
globals()['IsilonObjectProtectionUpdateRequestParams'] = IsilonObjectProtectionUpdateRequestParams
globals()['MssqlObjectProtectionUpdateRequestParams'] = MssqlObjectProtectionUpdateRequestParams
globals()['NetappObjectProtectionUpdateRequestParams'] = NetappObjectProtectionUpdateRequestParams
globals()['Office365UserMailboxObjectProtectionUpdateRequestParams'] = Office365UserMailboxObjectProtectionUpdateRequestParams
globals()['SlaRule'] = SlaRule
globals()['TimeOfDay'] = TimeOfDay
globals()['VmwareObjectProtectionUpdateRequestParams'] = VmwareObjectProtectionUpdateRequestParams
from cohesity_sdk.model.update_protected_objects_request import UpdateProtectedObjectsRequest


class TestUpdateProtectedObjectsRequest(unittest.TestCase):
    """UpdateProtectedObjectsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateProtectedObjectsRequest(self):
        """Test UpdateProtectedObjectsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateProtectedObjectsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
