"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.tdm_snapshot_task_params import TdmSnapshotTaskParams
globals()['TdmSnapshotTaskParams'] = TdmSnapshotTaskParams
from cohesity_sdk.model.common_tdm_task_request_paramsa69ce51b0ca64ed2802a748207466ace_tdm_snapshot_task_params_wrapper_all_of import CommonTdmTaskRequestParamsa69ce51b0ca64ed2802a748207466aceTdmSnapshotTaskParamsWrapperAllOf


class TestCommonTdmTaskRequestParamsa69ce51b0ca64ed2802a748207466aceTdmSnapshotTaskParamsWrapperAllOf(unittest.TestCase):
    """CommonTdmTaskRequestParamsa69ce51b0ca64ed2802a748207466aceTdmSnapshotTaskParamsWrapperAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonTdmTaskRequestParamsa69ce51b0ca64ed2802a748207466aceTdmSnapshotTaskParamsWrapperAllOf(self):
        """Test CommonTdmTaskRequestParamsa69ce51b0ca64ed2802a748207466aceTdmSnapshotTaskParamsWrapperAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonTdmTaskRequestParamsa69ce51b0ca64ed2802a748207466aceTdmSnapshotTaskParamsWrapperAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
