"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_source_registration_request_params1efc8a7f3ff24b728e3e57e74edbdd48 import CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48
from cohesity_sdk.cluster.model.common_source_registration_request_params1efc8a7f3ff24b728e3e57e74edbdd48_elastifile_registration_params_wrapper_all_of import CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapperAllOf
from cohesity_sdk.cluster.model.elastifile_registration_params import ElastifileRegistrationParams
globals()['CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48'] = CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48
globals()['CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapperAllOf'] = CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapperAllOf
globals()['ElastifileRegistrationParams'] = ElastifileRegistrationParams
from cohesity_sdk.model.common_source_registration_request_params1efc8a7f3ff24b728e3e57e74edbdd48_elastifile_registration_params_wrapper import CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapper


class TestCommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapper(unittest.TestCase):
    """CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapper(self):
        """Test CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48ElastifileRegistrationParamsWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
