"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.mongo_db_protection_group_params import MongoDBProtectionGroupParams
globals()['MongoDBProtectionGroupParams'] = MongoDBProtectionGroupParams
from cohesity_sdk.model.common_protection_group_request_params2384072a0e0849d28bd538044d7ffd40_mongo_db_protection_group_params_wrapper_all_of import CommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40MongoDBProtectionGroupParamsWrapperAllOf


class TestCommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40MongoDBProtectionGroupParamsWrapperAllOf(unittest.TestCase):
    """CommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40MongoDBProtectionGroupParamsWrapperAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40MongoDBProtectionGroupParamsWrapperAllOf(self):
        """Test CommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40MongoDBProtectionGroupParamsWrapperAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonProtectionGroupRequestParams2384072a0e0849d28bd538044d7ffd40MongoDBProtectionGroupParamsWrapperAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
