"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cohesity_sdk
from cohesity_sdk.api.external_connection import ExternalConnectionApi  # noqa: E501


class TestExternalConnectionApi(unittest.TestCase):
    """ExternalConnectionApi unit test stubs"""

    def setUp(self):
        self.api = ExternalConnectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_bifrost_connection(self):
        """Test case for create_bifrost_connection

        Create a connection of Bifrost on the cluster.  # noqa: E501
        """
        pass

    def test_create_rigel_connection(self):
        """Test case for create_rigel_connection

        Create a connection of Rigel on the cluster.  # noqa: E501
        """
        pass

    def test_delete_bifrost_connection(self):
        """Test case for delete_bifrost_connection

        Delete a connection of Bifrost.  # noqa: E501
        """
        pass

    def test_delete_rigel_connection(self):
        """Test case for delete_rigel_connection

        Delete a connection of Rigel.  # noqa: E501
        """
        pass

    def test_get_bifrost_connection(self):
        """Test case for get_bifrost_connection

        Get connections of Bifrost on the cluster.  # noqa: E501
        """
        pass

    def test_get_bifrost_connection_by_id(self):
        """Test case for get_bifrost_connection_by_id

        Get a connection of Bifrost by the id.  # noqa: E501
        """
        pass

    def test_get_rigel_connection(self):
        """Test case for get_rigel_connection

        Get connections of Rigel on the cluster.  # noqa: E501
        """
        pass

    def test_get_rigel_connection_by_id(self):
        """Test case for get_rigel_connection_by_id

        Get a connection of Rigel by the id.  # noqa: E501
        """
        pass

    def test_update_bifrost_connection(self):
        """Test case for update_bifrost_connection

        Update a connection of Bifrost.  # noqa: E501
        """
        pass

    def test_update_rigel_connection(self):
        """Test case for update_rigel_connection

        Update a connection of Rigel.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
