"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.helios_common_target_configuration import HeliosCommonTargetConfiguration
from cohesity_sdk.cluster.model.helios_replication_config_all_of import HeliosReplicationConfigAllOf
from cohesity_sdk.cluster.model.helios_retention import HeliosRetention
from cohesity_sdk.cluster.model.helios_target_schedule import HeliosTargetSchedule
globals()['HeliosCommonTargetConfiguration'] = HeliosCommonTargetConfiguration
globals()['HeliosReplicationConfigAllOf'] = HeliosReplicationConfigAllOf
globals()['HeliosRetention'] = HeliosRetention
globals()['HeliosTargetSchedule'] = HeliosTargetSchedule
from cohesity_sdk.model.helios_replication_config import HeliosReplicationConfig


class TestHeliosReplicationConfig(unittest.TestCase):
    """HeliosReplicationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeliosReplicationConfig(self):
        """Test HeliosReplicationConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HeliosReplicationConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
