"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cohesity_sdk
from cohesity_sdk.api.tags import TagsApi  # noqa: E501


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tag(self):
        """Test case for create_tag

        Create a Tag  # noqa: E501
        """
        pass

    def test_delete_tag(self):
        """Test case for delete_tag

        Delete a Tag  # noqa: E501
        """
        pass

    def test_get_tag_by_id(self):
        """Test case for get_tag_by_id

        Get Tag by id.  # noqa: E501
        """
        pass

    def test_get_tags(self):
        """Test case for get_tags

        Get tags based on filters.  # noqa: E501
        """
        pass

    def test_update_tag(self):
        """Test case for update_tag

        Update a Tag  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
