"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cohesity_sdk
from cohesity_sdk.api.protected_objects import ProtectedObjectsApi  # noqa: E501


class TestProtectedObjectsApi(unittest.TestCase):
    """ProtectedObjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProtectedObjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_perform_action_on_protect_objects(self):
        """Test case for perform_action_on_protect_objects

        Perform Actions on Protect Objects.  # noqa: E501
        """
        pass

    def test_protect_objects_of_any_type(self):
        """Test case for protect_objects_of_any_type

        Create Object Backup.  # noqa: E501
        """
        pass

    def test_update_protected_objects_of_any_type(self):
        """Test case for update_protected_objects_of_any_type

        Update Object Backup.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
