"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_source_registration_reponse_params4e87565f06374b6f_b2f229ffb710c669 import CommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669
from cohesity_sdk.cluster.model.common_source_registration_request_params1efc8a7f3ff24b728e3e57e74edbdd48_gpfs_registration_params_wrapper_all_of import CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48GpfsRegistrationParamsWrapperAllOf
from cohesity_sdk.cluster.model.gpfs_registration_params import GpfsRegistrationParams
from cohesity_sdk.cluster.model.object import Object
globals()['CommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669'] = CommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669
globals()['CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48GpfsRegistrationParamsWrapperAllOf'] = CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48GpfsRegistrationParamsWrapperAllOf
globals()['GpfsRegistrationParams'] = GpfsRegistrationParams
globals()['Object'] = Object
from cohesity_sdk.model.common_source_registration_reponse_params4e87565f06374b6f_b2f229ffb710c669_gpfs_registration_params_wrapper import CommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669GpfsRegistrationParamsWrapper


class TestCommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669GpfsRegistrationParamsWrapper(unittest.TestCase):
    """CommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669GpfsRegistrationParamsWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669GpfsRegistrationParamsWrapper(self):
        """Test CommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669GpfsRegistrationParamsWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonSourceRegistrationReponseParams4e87565f06374b6fB2f229ffb710c669GpfsRegistrationParamsWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
