"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_recovery_request_params728e9e8e_d3a3409e84ad_fc344fdac5ed_recover_kvm_params_wrapper_all_of import CommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverKvmParamsWrapperAllOf
from cohesity_sdk.cluster.model.common_recovery_response_params4f01ac8f10d64f8d_b96c_c3e53f5aa592 import CommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592
from cohesity_sdk.cluster.model.creation_info import CreationInfo
from cohesity_sdk.cluster.model.recover_kvm_params import RecoverKvmParams
from cohesity_sdk.cluster.model.tenant import Tenant
globals()['CommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverKvmParamsWrapperAllOf'] = CommonRecoveryRequestParams728e9e8eD3a3409e84adFc344fdac5edRecoverKvmParamsWrapperAllOf
globals()['CommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592'] = CommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592
globals()['CreationInfo'] = CreationInfo
globals()['RecoverKvmParams'] = RecoverKvmParams
globals()['Tenant'] = Tenant
from cohesity_sdk.model.common_recovery_response_params4f01ac8f10d64f8d_b96c_c3e53f5aa592_recover_kvm_params_wrapper import CommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592RecoverKvmParamsWrapper


class TestCommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592RecoverKvmParamsWrapper(unittest.TestCase):
    """CommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592RecoverKvmParamsWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592RecoverKvmParamsWrapper(self):
        """Test CommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592RecoverKvmParamsWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonRecoveryResponseParams4f01ac8f10d64f8dB96cC3e53f5aa592RecoverKvmParamsWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
