"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_source_registration_request_params1efc8a7f3ff24b728e3e57e74edbdd48_hive_source_registration_params_wrapper_all_of import CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48HiveSourceRegistrationParamsWrapperAllOf
from cohesity_sdk.cluster.model.common_source_registration_request_params87a8b0b01c2c4381_b6c93209126747be import CommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747be
from cohesity_sdk.cluster.model.hive_source_registration_params import HiveSourceRegistrationParams
globals()['CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48HiveSourceRegistrationParamsWrapperAllOf'] = CommonSourceRegistrationRequestParams1efc8a7f3ff24b728e3e57e74edbdd48HiveSourceRegistrationParamsWrapperAllOf
globals()['CommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747be'] = CommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747be
globals()['HiveSourceRegistrationParams'] = HiveSourceRegistrationParams
from cohesity_sdk.model.common_source_registration_request_params87a8b0b01c2c4381_b6c93209126747be_hive_source_registration_params_wrapper import CommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747beHiveSourceRegistrationParamsWrapper


class TestCommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747beHiveSourceRegistrationParamsWrapper(unittest.TestCase):
    """CommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747beHiveSourceRegistrationParamsWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747beHiveSourceRegistrationParamsWrapper(self):
        """Test CommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747beHiveSourceRegistrationParamsWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonSourceRegistrationRequestParams87a8b0b01c2c4381B6c93209126747beHiveSourceRegistrationParamsWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
