- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:
  - name: Update AP site to controller
    cisco.dnac.wireless_provision_device_update:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_debug: "{{dnac_debug}}"
      payload:
      - deviceName: "C9K-Branch-SFO.dcloud.cisco.com"
        managedAPLocations:
        - "Global/San Francisco"
    register: result



  - name: Show result
    ansible.builtin.debug:
      msg: "{{ result }}"