
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/mitol/google_sheets:mitol-django-google-sheets

from setuptools import setup

setup(**{
    'authors': [
        'MIT Office of Open Learning <mitx-devops@mit.edu>',
    ],
    'classifiers': [
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
    'description': 'Core library to handle Google Sheets integrations in Django',
    'install_requires': (
        'mitol-django-common~=2.2.4',
        'setuptools',
    ),
    'license': 'BSD 3-Clause License',
    'name': 'mitol-django-google-sheets',
    'namespace_packages': (
        'mitol',
    ),
    'package_data': {
        'mitol.google_sheets': (
            'CHANGELOG.md',
            'README.md',
            'py.typed',
        ),
    },
    'packages': (
        'mitol',
        'mitol.google_sheets',
    ),
    'version': '2.2.5',
    'zip_safe': True,
})
