import os

WORDNET_REPLACE = eval(os.getenv('WORDNET_REPLACE', 'False'))
HE_SHE_SPEAKER_GUESS = eval(os.getenv('HE_SHE_SPEAKER_GUESS', 'True'))
SPEAKER_PLACEMENT_GUESS = eval(os.getenv('SPEAKER_PLACEMENT_GUESS', 'True'))

PREPROCESS_NORMALIZE_SPELLING = eval(os.getenv('PREPROCESS_NORMALIZE_SPELLING', 'True'))
PREPROCESS_NUMBER_CONVERT = eval(os.getenv('PREPROCESS_NUMBER_CONVERT', 'True'))
PREPROCESS_REPLACE_CONTRACTIONS = eval(os.getenv('PREPROCESS_REPLACE_CONTRACTIONS', 'True'))
PREPROCESS_REPLACE_ELLIPSIS = eval(os.getenv('PREPROCESS_REPLACE_ELLIPSIS', 'True'))
PREPROCESS_REMOVE_DECIMAL_SEPARATORS = eval(os.getenv('PREPROCESS_REMOVE_DECIMAL_SEPARATORS', 'True'))
PREPROCESS_REMOVE_STOPWORDS = eval(os.getenv('PREPROCESS_REMOVE_STOPWORDS', 'False'))

ASSUMED_LANGUAGE = os.getenv('ASSUMED_LANGUAGE', None)

OPTIMIZE_FOR = os.getenv('OPTIMIZE_FOR', 'speed')  # speed, memory
