[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tawazi"
authors = [{name = "Bashir ABDEL WAHED", email = "bashir@mindee.co"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = ["version", "description"]
requires-python = ">=3.8"
dependencies = [
    "networkx >=2.6.3"
]

[project.optional-dependencies]
test = [
    "pre-commit",
    "matplotlib",
    "pytest",
    "black ==22.3.0",
    "mypy",
    "flake8"
]

[project.urls]
#Documentation = "something"
#Source = "Something"
