[tool.poetry]
name = "pygoodwe"
version = "0.0.18"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

classifiers = [
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent"
]
keywords = [
    "goodwe",
    "solar",
    "api",
    "pygoodwe"
]
readme = "README.md"


[project.urls]
documentation = "https://yaleman.github.io/pygoodwe/"
homepage = "https://github.com/yaleman/pygoodwe"
repository = "https://github.com/yaleman/pygoodwe"


[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
types-requests = "^2.27.31"
pylint = "^2.14.3"
pytest = "^7.1.2"
mypy = "^0.961"
black = "^22.3.0"
pylint-pytest = "^1.1.2"
mkdocs = "^1.3.0"
mkdocs-material = "^8.3.8"
mkdocstrings = "^0.19.0"
mkdocstrings-python = "^0.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
disable="W0511"
max-line-length=150
load-plugins="pylint_pytest"
