[tool.poetry]
name = "cleanup-utils"
version = "0.1.2"
description = "Utility scripts to clean up your system"
authors = ["Teddy Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "cleanup_utils"}]
license = "MIT"
homepage = "https://github.com/tddschn/cleanup-utils"
repository = "https://github.com/tddschn/cleanup-utils"
classifiers = [
    "Topic :: Utilities"
]
keywords = ["cleanup", "utils"]

[tool.poetry.scripts]
mac_clean_library_cache = "cleanup_utils.mac_clean_library_cache:main"
macclc = "cleanup_utils.mac_clean_library_cache:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tddschn/cleanup-utils/issues"

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"


[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
rich = "^12.4.4"
ipython = "^8.4.0"
better-exceptions = "^0.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
