
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-23T01:09:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f9e0cb184ce8e815d2c72e60697b60b2316fa66",
 "version": "0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
