
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-22T15:24:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ff74be8f7b836219f9490e8e44bc08f506d4518",
 "version": "0.2.9.post0.dev13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
