[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eoglib"
version = "0.2.1"
authors = [
    { name="Roberto Antonio Becerra García", email="idertator@gmail.com" },
]
description = "Electrooculography (EOG) signals processing package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    'Intended Audience :: Education',
    'Intended Audience :: Healthcare Industry',
    'Intended Audience :: Science/Research',
    'License :: Other/Proprietary License',
    'Natural Language :: English',
    'Operating System :: POSIX :: Linux',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'Topic :: Scientific/Engineering :: Medical Science Apps.',
    'Programming Language :: Python :: 3.9',
]

[project.urls]
"Homepage" = "https://gitlab.com/eyeres/eoglib"
"Bug Tracker" = "https://gitlab.com/eyeres/eoglib/-/issues"
