[tool.poetry]
name = "asyncio-ttl-cache"
version = "0.0.3"
description = "Async TTL cache"
authors = ["Pony Ma <mtf201013@gmail.com>"]
packages = [
    { include = "asyncio_ttl_cache" }
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.18.3"
aiomock = "^0.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
