from _typeshed import Incomplete
from edgeiq._production_client import PRODUCTION_CLIENT as PRODUCTION_CLIENT
from edgeiq.edge_tools import to_json_serializable as to_json_serializable

class QRCodeDetectionPrediction:
    def __init__(self, box, info) -> None: ...
    def __eq__(self, other): ...
    @property
    def box(self): ...
    @property
    def info(self): ...

class QRCodeDetectionResults:
    def __init__(self, predictions, image) -> None: ...
    def __eq__(self, other): ...
    @property
    def predictions(self): ...
    @property
    def image(self): ...
    def markup_image(self): ...

RESULT_TYPE: Incomplete

class QRCodeDetection:
    qrcode_reader: Incomplete
    def __init__(self) -> None: ...
    def localize_decode(self, image): ...
    def publish_analytics(self, results, tag: Incomplete | None = ...) -> None: ...
