[tool.poetry]
name = "cfg1"
version = "0.0.1"
description = "A configuration library for Python3 projects"
authors = ["Dan Sikes <dansikes7@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyaml = "^21.10.1"
python-box = "^6.0.2"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
