[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "c1algo1"
version = "0.0.1"
authors = [
  { name="SENG499 Company 1", email="benjaminaustin@uvic.ca" },
]
description = "scheduler algo"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/seng499-company1/algorithm-1"
"Bug Tracker" = "https://github.com/seng499-company1/algorithm-1/issues"