[project]
name = "aiovalorant"
description = "An async wrapper for Valorant API."
version = "0.1.0"
authors = [
    { name = "Shinobou", email = "86394469+Shinobou@users.noreply.github.com" }
]
dependencies = [
    "pydantic~=1.9.1",
    "aiosonic~=0.14.1"
]

[project.optional-dependencies]
dev = [
    "black",
    "mypy"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]