
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-27T10:36:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "19b86bc37dc9e2de903e5a6ee7a6247cf893c138",
 "version": "22.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
