[tool.poetry]
name = "comanda_daunov"
version = "1.0.0"
description = "rabotay plz"
authors = ["NuatStanskiy <smiril13@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
