[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chiral_db_grpc_client"
version = "0.0.1"
authors = [
  { name="Qin Wan", email="rogerwq@gmail.com" },
]
description = "ChiralDB gRPC client"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/chiral-data/chiral-db-grpc-client"