
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-22T19:37:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "90ec8d4549acffe1f3f70b3fb8b74fb7e679e5c5",
 "version": "0.2.9.post0.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
