[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line_length = 79

[tool.isort]
profile = "black"
src_paths = ["cutyx", "tests", "setup.py"]
line_length = 79

[tool.darker]
line_length = 79
src = [
    "cutyx",
    "tests",
    "setup.py"
]
revision = "master"
diff = true
check = true
isort = true
log_level = "INFO"

[tool.mypy]
python_version = "3.10"
files = ["cutyx/**/*.py", "tests/**/*.py", "setup.py"]
pretty = true
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov-report html --cov=cutyx"
testpaths = [
    "tests",
    "cutyx",
]
doctest_optionflags = "NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL NUMBER"