
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-27T03:58:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a20a34c960cf36920da1f73a189d9a2e004056c3",
 "version": "1.16.0.post.dev812"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
