
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-21T19:25:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "02db2719de8b5e3c6941cc89702504f33bb98cd8",
 "version": "0.2.8.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
