"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.chat_user_username_reference_all_of import ChatUserUsernameReferenceAllOf


class TestChatUserUsernameReferenceAllOf(unittest.TestCase):
    """ChatUserUsernameReferenceAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatUserUsernameReferenceAllOf(self):
        """Test ChatUserUsernameReferenceAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChatUserUsernameReferenceAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
