"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.chat_user_properties import ChatUserProperties
from openapi_client.model.message_link_properties import MessageLinkProperties
from openapi_client.model.message_mention_properties import MessageMentionProperties
globals()['ChatUserProperties'] = ChatUserProperties
globals()['MessageLinkProperties'] = MessageLinkProperties
globals()['MessageMentionProperties'] = MessageMentionProperties
from openapi_client.model.text_chat_user_message_properties_all_of import TextChatUserMessagePropertiesAllOf


class TestTextChatUserMessagePropertiesAllOf(unittest.TestCase):
    """TextChatUserMessagePropertiesAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextChatUserMessagePropertiesAllOf(self):
        """Test TextChatUserMessagePropertiesAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextChatUserMessagePropertiesAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
