"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.messages_api import MessagesApi  # noqa: E501


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_message(self):
        """Test case for delete_message

        Delete a message  # noqa: E501
        """
        pass

    def test_delete_messages(self):
        """Test case for delete_messages

        Delete messages  # noqa: E501
        """
        pass

    def test_retrieve_message(self):
        """Test case for retrieve_message

        Retrieve a message  # noqa: E501
        """
        pass

    def test_retrieve_message_read_receipts(self):
        """Test case for retrieve_message_read_receipts

        Retrieve message read receipts  # noqa: E501
        """
        pass

    def test_retrieve_messages(self):
        """Test case for retrieve_messages

        Retrieve messages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
