"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.imports_api import ImportsApi  # noqa: E501


class TestImportsApi(unittest.TestCase):
    """ImportsApi unit test stubs"""

    def setUp(self):
        self.api = ImportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_import_channel_members(self):
        """Test case for import_channel_members

        Import channel members  # noqa: E501
        """
        pass

    def test_import_channels(self):
        """Test case for import_channels

        Import channels  # noqa: E501
        """
        pass

    def test_import_messages(self):
        """Test case for import_messages

        Import messages  # noqa: E501
        """
        pass

    def test_import_users(self):
        """Test case for import_users

        Import users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
