"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.function_versions_api import FunctionVersionsApi  # noqa: E501


class TestFunctionVersionsApi(unittest.TestCase):
    """FunctionVersionsApi unit test stubs"""

    def setUp(self):
        self.api = FunctionVersionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_function_version(self):
        """Test case for retrieve_function_version

        Retrieve a chat function version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
