"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.links import Links
from openapi_client.model.page_metadata import PageMetadata
from openapi_client.model.paged_model_channel_resource_embedded import PagedModelChannelResourceEmbedded
globals()['Links'] = Links
globals()['PageMetadata'] = PageMetadata
globals()['PagedModelChannelResourceEmbedded'] = PagedModelChannelResourceEmbedded
from openapi_client.model.paged_model_channel_resource import PagedModelChannelResource


class TestPagedModelChannelResource(unittest.TestCase):
    """PagedModelChannelResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagedModelChannelResource(self):
        """Test PagedModelChannelResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PagedModelChannelResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
