"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.text_chat_user_message_import import TextChatUserMessageImport
from openapi_client.model.text_system_message_import import TextSystemMessageImport
globals()['TextChatUserMessageImport'] = TextChatUserMessageImport
globals()['TextSystemMessageImport'] = TextSystemMessageImport
from openapi_client.model.message_import import MessageImport


class TestMessageImport(unittest.TestCase):
    """MessageImport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageImport(self):
        """Test MessageImport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageImport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
