"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.runtime_api import RuntimeApi  # noqa: E501


class TestRuntimeApi(unittest.TestCase):
    """RuntimeApi unit test stubs"""

    def setUp(self):
        self.api = RuntimeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_nodejs_runtime_function(self):
        """Test case for create_nodejs_runtime_function

        Create a NodeJS chat runtime function  # noqa: E501
        """
        pass

    def test_retrieve_nodejs_runtime(self):
        """Test case for retrieve_nodejs_runtime

        Retrieve NodeJS chat runtime  # noqa: E501
        """
        pass

    def test_retrieve_nodejs_runtime_functions(self):
        """Test case for retrieve_nodejs_runtime_functions

        Retrieve NodeJS chat runtime functions  # noqa: E501
        """
        pass

    def test_update_nodejs_runtime_dependencies(self):
        """Test case for update_nodejs_runtime_dependencies

        Update NodeJS chat runtime NPM dependencies  # noqa: E501
        """
        pass

    def test_update_nodejs_runtime_environment_variables(self):
        """Test case for update_nodejs_runtime_environment_variables

        Update NodeJS chat runtime environment variables  # noqa: E501
        """
        pass

    def test_update_nodejs_runtime_initialization_script(self):
        """Test case for update_nodejs_runtime_initialization_script

        Update NodeJS chat runtime initialization script  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
