"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.chat_user_presence_properties_patch import ChatUserPresencePropertiesPatch


class TestChatUserPresencePropertiesPatch(unittest.TestCase):
    """ChatUserPresencePropertiesPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatUserPresencePropertiesPatch(self):
        """Test ChatUserPresencePropertiesPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChatUserPresencePropertiesPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
