"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.add_channel_member_request import AddChannelMemberRequest
from openapi_client.model.create_file_message_resource import CreateFileMessageResource
from openapi_client.model.create_text_message_resource import CreateTextMessageResource
globals()['AddChannelMemberRequest'] = AddChannelMemberRequest
globals()['CreateFileMessageResource'] = CreateFileMessageResource
globals()['CreateTextMessageResource'] = CreateTextMessageResource
from openapi_client.model.create_message_resource import CreateMessageResource


class TestCreateMessageResource(unittest.TestCase):
    """CreateMessageResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateMessageResource(self):
        """Test CreateMessageResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateMessageResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
