"""
    ChatKitty Platform REST API

    Platform REST API OpenAPI specification (OAS).  See the Interactive Docs to try ChatKitty API methods without writing code,  and get the complete schema of resources exposed by the API.  # noqa: E501

    The version of the OpenAPI document: v1.15.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.create_text_message_resource_all_of import CreateTextMessageResourceAllOf
from openapi_client.model.message_import import MessageImport
from openapi_client.model.text_chat_user_message_import import TextChatUserMessageImport
from openapi_client.model.text_system_message_import import TextSystemMessageImport
globals()['CreateTextMessageResourceAllOf'] = CreateTextMessageResourceAllOf
globals()['MessageImport'] = MessageImport
globals()['TextChatUserMessageImport'] = TextChatUserMessageImport
globals()['TextSystemMessageImport'] = TextSystemMessageImport
from openapi_client.model.text_system_message_import import TextSystemMessageImport


class TestTextSystemMessageImport(unittest.TestCase):
    """TextSystemMessageImport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextSystemMessageImport(self):
        """Test TextSystemMessageImport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextSystemMessageImport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
