[tool.poetry]
name = "py-appdata"
version = "0.0.3"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/gedemagt/appdata"
description = "Small utility library to provide easy access to files and key-value store in an application directory"
authors = ["Jesper Jensen <mail@jeshj.com>"]
packages = [
    { include = "appdata" }
]


[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"