# Generated by Django 3.2.13 on 2022-06-22 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('giant_faqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQBlock',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='giant_faqs_faqblock', serialize=False, to='cms.cmsplugin')),
                ('faqs', models.ManyToManyField(to='giant_faqs.FAQ')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
