#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pbarticles']

package_data = \
{'': ['*']}

setup(name='pbarticles',
      version='0.1',
      description='A package to make a PDF from Pybites articles',
      author=None,
      author_email='Bob Belderbos <bob@pybit.es>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
