agent_name: gym_aea
author: fetchai
version: 0.25.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: QmNZkqQZByU5yn18ELka8TAyypiRxhHjAfMSdZfUy9mRwy
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:QmQgtAmVUSvjbFXth3HMabP4o696qTh2fyzE9SxSSuibL3
contracts: []
protocols:
- fetchai/default:1.0.0:QmYNdsSrdKRvJGKjAbREuvkjGXgnanDjxCBS8CfJb9fzr1
- fetchai/gym:1.0.0:QmSd1SpzSV1U1LyQJ7C5hrZT5c7rQXfJLez5fGBnveFLVx
- fetchai/state_update:1.0.0:QmZ9dxrmQTZCpA5VuamxBticK4CUZAfPsraTodksvmcqHx
- open_aea/signing:1.0.0:QmRL1Qt5TEzbw6xRn3grz1fe22uM761AXL8UQ8QvGmQn8K
skills:
- fetchai/gym:0.20.0:QmTqPWwPXVPRH1Rg9xq4obCHnUpXAyTCoo8cBEcyz4YVfg
default_connection: fetchai/gym:0.19.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <2.0.0,>=1.0.0
