
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-27T14:52:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f731c246c7d1e1148d764c7e2a81153599808215",
 "version": "4.0.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
