# Generated by Django 3.2.13 on 2022-06-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_membership_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderEMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('footer', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Reminder email',
                'verbose_name_plural': 'Reminder emails',
            },
        ),
        migrations.CreateModel(
            name='InvitationEMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('footer', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Invitation email',
                'verbose_name_plural': 'Invitation emails',
            },
        ),
    ]
