[tool.poetry]
name = "geosampler"
version = "0.1.0"
description = "A simple way to collect samples for social sciences experiments"
authors = ["Gloria Macia <gloria.macia@roche.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.0"
pandas = "^1.4.3"
folium = "^0.12.1"
tqdm = "^4.64.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.3.0"
isort = "^5.10.1"
ipykernel = "^6.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
