[tool.poetry]
name = "CardTrader-Wrapper"
version = "0.2.0"
description = "A Python wrapper for the CardTrader API."
license = "GPL-3.0-or-later"
authors = ["Buried-In-Code <BuriedInCode@tuta.io>"]
maintainers = ["Buried-In-Code <BuriedInCode@tuta.io>"]
readme = "README.md"
repository = "https://github.com/Buried-In-Code/CardTrader-Wrapper"
packages = [
    { include = "cardtrader" }
]
include = [
    { path = "tests", format = "sdist" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.0"
ratelimit = "^2.2.1"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
tox = "^3.25.0"
tox-pyenv = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = []

[tool.coverage.run]
source = ["cardtrader"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = ["--cov", "-x"]
