[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "word2emoji"
version = "0.1.4"
description = 'Convert any word in the English language to an emoji'
readme = "README.md"
authors = [
  { name = "Douwe Osinga", email = "douwe.osinga@gmail.com" },
]
requires-python = ">=3.7"
license = { file = "LICENSE" }
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

dependencies = ["nltk"]
keywords = ["emoji", "nlp", "text"]

[project.urls]
Documentation = "https://github.com/DOsinga/word2emoji#readme"
Issues = "https://github.com/DOsinga/word2emoji/issues"
Source = "https://github.com/DOsinga/word2emoji"

