
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-21T23:15:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5423fb595389c20f52529e8739578e7e5d7d66a",
 "version": "0.0.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
