# Build Configuration for python package deployment to pypi
image: python:3.9

definitions:
  steps:
    - step: &lint
        caches:
          - pip
        name: Lint
        script:
          - pip install pre-commit
          - pre-commit install
          - pre-commit run --all-files
    - step: &test
        name: Test
        script:
          - pip install tox
          - tox -e py39
    - step: &scan
        caches:
          - pip
        name: Scan
        script:
          - pip install .
          - pip install safety
          - safety check --full-report ${SAFETY_IGNORE}
    - step: &docs
        name: Build Docs
        caches:
          - pip
        script:
          - apt update && apt -y install graphviz
          - pip install .[docs]
          - sphinx-build --color -W --keep-going -b html docs docs/_build/html
    - step: &publish
        name: Publish
        script:
          - python setup.py sdist
          - pip install twine
          - twine upload dist/*

pipelines:
  default:
    - step: *lint
    - step: *test
    - step: *docs
    - step: *scan
  tags:
    'v*':
      - step: *lint
      - step: *test
      - step: *docs
      - step: *scan
      - step: *publish
