[build-system]
requires = [
    "setuptools>=61",
    "wheel",
    "setuptools_scm>=6.4"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tse_datatools/_version.py"

[tool.pytest.ini_options]
addopts = "--cov=readimc --cov-report xml:coverage.xml"
