REPLACEMENTS = {
    'faux pas': 'blunder',
    'and also': 'and',
    'thank you': 'thanks',
    'in order to': 'to',
    'a great help': 'helpful',
    'absolutely necessary': 'necessary',
    'in regard to': 'regarding',
    'in regards to': 'regarding',
    'i\'m': 'i am',
    'a bit difficult': 'difficult',
    'per annum': 'yearly',
    'a good thing': 'good',
    'sinn féin': 'sinn_fein',
    'don\'t': 'do not',
    'it\'s': 'it is',
    'a great deal': 'a lot',
    'fully aware': 'aware',
    'motor car': 'car',
    'mr.': 'mr',
    'mrs.': 'mrs',
    'dr.': 'dr',
    'ms.': 'ms',
    'Mr.': 'Mr',
    'Mrs.': 'Mrs',
    'Dr.': 'Dr',
    'Ms.': 'Ms',
    'in favour': 'in_favour',
    'general election': 'general_election',
    'reap the benefit': 'benefit',
    'much longer': 'longer',
    'a great help': 'helpful',
    'absolutely necessary': 'necessary',
    'in regard to': 'regarding',
    'in regards to': 'regarding',
    'i\'m': 'i am',
    'a bit difficult': 'difficult',
    'per annum': 'yearly',
    'a good thing': 'good',
    'sinn féin': 'sinn_fein',
    'don\'t': 'do not',
    'it\'s': 'it is',
    'a great deal': 'a lot',
    'fully aware': 'aware',
    'motor car': 'car',

    # need to do by word so these one word ones can be used
    #'yeah': 'yes',
    #'yep': 'yes',
    #'nope': 'no',
    #'nah': 'no',
    #'da': 'father',
    #'dad': 'father',
    #'daddy': 'father',
    #'ma': 'mother',
    #'mum': 'mother',
    #'mam': 'mother',
    #'mammy': 'mother'
}  # TODO: test this

for k, v in REPLACEMENTS.copy().items():
    REPLACEMENTS[k.capitalize()] = v.capitalize()
