
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-28T13:58:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8363203b49440b0fc7602b1d3420ba8684d0d218",
 "version": "1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
