[tool.poetry]
name = "boggle"
version = "0.1.1"
description = "Generate boards for the game boggle"
authors = ["Max Levine <max@maxlevine.co.uk>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://gitlab.com/bmaximuml/boggle"
documentation = "https://gitlab.com/bmaximuml/boggle"
keywords = [
    "boggle",
    "game",
    "board game",
    "word game"
]

[tool.poetry.dependencies]
python = "^3.7"
tabulate = "^0.8.10"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[tool.poetry.scripts]
boggle = "boggle.board:board_cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
