# Asteroid constants
SPECTRAL_TYPES = ["C", "Cm", "Ci", "Cs", "Cms", "Cis", "S", "Sm", "Si", "M", "I"]
RARITIES = ["Common", "Uncommon", "Rare", "Superior", "Exceptional", "Incomparable"]
SIZES = ["Small", "Medium", "Large", "Huge"]

# Crew member constants
CREW_COLLECTIONS = ["Arvad Specialist", "Arvad Citizen", "Arvad Leadership"]
CREW_CLASSES = ["Pilot", "Engineer", "Miner", "Merchant", "Scientist"]
CREW_TITLES = [
    "Communications Officer",
    "Teaching Assistant",
    "Librarian",
    "Nurse",
    "Public Safety Officer",
    "Warehouse Worker",
    "Maintenance Technician",
    "Systems Administrator",
    "Structural Engineer",
    "Farmer",
    "Line Cook",
    "Artist",
    "Block Captain",
    "Observatory Technician",
    "Teacher",
    "Historian",
    "Physician Assistant",
    "Security Officer",
    "Logistics Specialist",
    "Electrician",
    "Software Engineer",
    "Life Support Engineer",
    "Field Botanist",
    "Section Cook",
    "Author",
    "Delegate",
    "Cartographer",
    "Professor",
    "Archivist",
    "Resident Physician",
    "Tactical Officer",
    "Warehouse Manager",
    "EVA Technician",
    "Embedded Engineer",
    "Propulsion Engineer",
    "Nutritionist",
    "Kitchen Manager",
    "Musician",
    "Councilor",
    "Navigator",
    "Distinguished Professor",
    "Curator",
    "Physician",
    "Intelligence Officer",
    "Logistics Manager",
    "Facilities Supervisor",
    "Systems Architect",
    "Reactor Engineer",
    "Plant Geneticist",
    "Chef",
    "Actor",
    "Justice",
    "Chief Navigator",
    "Provost",
    "Chief Archivist",
    "Chief Medical Officer",
    "Head of Security",
    "Chief Logistics Officer",
    "Chief Steward",
    "Chief Technology Officer",
    "Head of Engineering",
    "Chief Botanist",
    "Chief Cook",
    "Entertainment Director",
    "High Commander",
]

CREW_SEX = ["Male", "Female"]
CREW_OUTFIT = [
    "Light Spacesuit - Blue",
    "Light Spacesuit - Purple",
    "Light Spacesuit - Orange",
    "Heavy Spacesuit - Red",
    "Heavy Spacesuit - Black",
    "Heavy Spacesuit - Blue",
    "Lab Coat - White",
    "Lab Coat - Yellow",
    "Lab Coat - Green",
    "Tool Vest - Orange",
    "Tool Vest - Green",
    "Tool Vest - Yellow",
    "Jacket - Red",
    "Jacket - Green",
    "Jacket - Black",
    "Stationwear - Red",
    "Stationwear - Green",
    "Stationwear - Black",
    "Light Spacesuit - Navigation",
    "Stationwear - Education",
    "Stationwear - Archival",
    "Lab Coat - Medical",
    "Heavy Spacesuit - Security",
    "Light Spacesuit - Logistics",
    "Tool Vest - Maintenance",
    "Light Spacesuit - Technology",
    "Tool Vest - Engineering",
    "Lab Coat - Botany",
    "Jacket - Cooking",
    "Jacket - Entertainment",
    "Stationwear - Commander",
]

CREW_HAIR = [
    "Bald",
    "Mohawk",
    "Slickback",
    "Curly",
    "Buzz",
    "Top Knot",
    "Bun",
    "Long",
    "Ponytail",
    "Pixie",
    "Double Bun",
    "Shoulder",
]

CREW_HAIR_COLOR = ["Red", "Gray", "Brown", "Blonde", "Black"]
CREW_FACIAL_FEATURE = [
    "Scar",
    "Piercing",
    "Long Beard",
    "Full Beard",
    "Circle Beard",
    "Handlebar Mustache",
    "Mustache",
]

CREW_HEAD_PIECE = [
    "Welding Goggles",
    "AR Glasses",
    "Eyepatch",
    "Mask",
    "Helmet",
    "Navigation Goggles",
    "Spectacles",
    "Archival Glasses",
    "Medical Glasses",
    "Headset",
    "Earmuffs",
    "Technology Glasses",
    "Botany Glasses",
    "Chef Hat",
    "Eyepatch - Orange",
    "Eyepatch - Gold",
]
CREW_BONUS_ITEM = [
    "Glow",
    "Drone - Gray",
    "Drone - Orange",
    "Drone - Green",
    "Drone - Yellow",
    "Drone - Medical",
    "Drone - Technology",
    "Drone - Commander",
]
