
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-27T16:32:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "896cf44d0d205cce0c019414b134dc123850fd88",
 "version": "1.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
