[tool.poetry]
name = "dh-facebook-client"
version = "0.1.2"
description = "Simple client for interacting with the Facebook Graph API"
authors = ["pchisholm <chisholm.p@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
backoff = "^1.11.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^6.2.5"
isort = "^5.10.1"
black = "^21.11b1"
mypy = "^0.910"
types-requests = "^2.26.1"
responses = "^0.16.0"
coverage = "^6.2"

[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py36']

[tool.isort]
line_length = 100
include_trailing_comma = true
multi_line_output = 3
