[tool.poetry]
name = "macos-utils"
version = "0.1.1"
description = ""
authors = ["Teddy Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "macos_utils"}]
license = "MIT"
homepage = "https://github.com/tddschn/macos-utils"
repository = "https://github.com/tddschn/macos-utils"
classifiers = [
    "Topic :: Utilities"
]
keywords = ["macos", "utils"]

[tool.poetry.scripts]
spotlight-exclude = "macos_utils.add_dir_to_spotlight_exclusions_list:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tddschn/macos-utils/issues"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
rich = "^12.4.4"
ipython = "^8.4.0"
better-exceptions = "^0.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
