[tool.poetry]
name = "aawscd"
version = "1.0.1"
description = "Utilities for the Aaware Sound Capture platform"
authors = ["Chris Eddington <chris@aaware.com>", "Jason Calderwood <jason@aaware.com>"]
maintainers = ["Chris Eddington <chris@aaware.com>", "Jason Calderwood <jason@aaware.com>"]
homepage = "https://aaware.com"
license = "GPL-3.0-only"
readme = "README.rst"
include = []

[tool.poetry.scripts]
aawscd_copycat = 'aawscd.aawscd_copycat:main'
aawscd_getconf = 'aawscd.aawscd_getconf:main'
aawscd_pdcap = 'aawscd.aawscd_pdcap:main'
aawscd_probmon = 'aawscd.aawscd_probmon:main'
aawscd_probwrite = 'aawscd.aawscd_probwrite:main'
aawscd_setdirection = 'aawscd.aawscd_setdirection:main'
aawscd_wwclient = 'aawscd.aawscd_wwclient:main'
aawscd_wwrecord = 'aawscd.aawscd_wwrecord:main'

[tool.poetry.dependencies]
PyYAML = "^6.0"
docopt = "^0.6"
h5py = "^3"
paho-mqtt = "^1.6.1"
pyaaware = "^1.3.17"
python = ">=3.8,<3.11"
tqdm = "^4.62"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
