[tool.poetry]
name = "mosaic-client"
version = "0.1.0"
description = "Easy consumption of SOAP interfaces provided by E-PIX and gPAS of the MOSAIC suite"
authors = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
maintainers = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
license = "MIT"
readme = "README.md"
documentation= "https://pprl.gitlab.io/mosaic-client-python/"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.10"
zeep = "^4.1.0"
marshmallow = "^3.16.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^4.0.1"
pdoc3 = "^0.10.0"
Faker = "^13.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
