
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-23T15:52:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c3f9bdb359995657ad6ec99b3b726fdf3a1230f",
 "version": "0.26.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
