# Generated by Django 4.0.4 on 2022-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_juniper_srx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypolicy',
            name='default_action',
            field=models.CharField(default='permit', max_length=100),
        ),
        migrations.AlterField(
            model_name='securitypolicyrule',
            name='action',
            field=models.CharField(default='permit', max_length=100),
        ),
        migrations.AlterField(
            model_name='securitypolicyrule',
            name='application',
            field=models.CharField(default='permit', max_length=100),
        ),
    ]
