# Generated by Django 4.0.4 on 2022-06-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_juniper_srx', '0004_securitypolicyrule_comments_securityzone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitypolicy',
            name='site',
        ),
        migrations.RemoveField(
            model_name='securitypolicy',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='site',
        ),
        migrations.RemoveField(
            model_name='securitypolicyrule',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='securityzone',
            name='site',
        ),
        migrations.RemoveField(
            model_name='securityzone',
            name='tenant',
        ),
    ]
