# Generated by Django 4.0.4 on 2022-06-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_juniper_srx', '0005_remove_securitypolicy_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityzone',
            name='default_action',
        ),
    ]
