# Generated by Django 4.0.4 on 2022-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_juniper_srx', '0006_remove_securityzone_default_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityzone',
            name='match_interfaces',
        ),
        migrations.AddField(
            model_name='securityzone',
            name='interfaces',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
