
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-21T19:05:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd005e56aed9a70e4499af9c200ab91d90944aa6",
 "version": "0.2.8.post0.dev12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
