
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-28T13:43:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9c8a644fc0d7f4bca4d6d7ee28ed61b222e6f6f",
 "version": "0.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
