
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-24T03:28:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfece49afc97aeb4dfb68adc5db505bf506151ed",
 "version": "1.16.0.post.dev804"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
