[tool.poetry]
name = "startfile"
version = "1.0.0"
description = "hi this help from star python"
authors = ["None"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
