from .object_tracking import DEFAULT_DEREGISTER_FRAMES as DEFAULT_DEREGISTER_FRAMES, DEFAULT_MAX_DISTANCE as DEFAULT_MAX_DISTANCE, DEFAULT_MIN_INERTIA as DEFAULT_MIN_INERTIA, TrackerAlgorithm as TrackerAlgorithm, TrackingResults as TrackingResults
from _typeshed import Incomplete

class CentroidTracker:
    def __init__(self, deregister_frames=..., max_distance=..., min_inertia=..., enter_cb: Incomplete | None = ..., exit_cb: Incomplete | None = ..., history_length: int = ..., **kwargs) -> None: ...
    def update(self, predictions): ...
    def remove_id(self, id) -> None: ...
