
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-24T10:00:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f29577159616348a35961f5be570ce1f3fdffdff",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
