[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "prediction_coefficient"
version = "0.0.0"
authors = [
  { name="Lance Edward Darragh", email="ForDataScience@gmx.com" },
]
description = "A categorical correlation coefficient that's in the same range for all pairs of variables (from 0 to 1), regardless of their degrees of freedom or the chosen confidence level."
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Operating System :: OS Independent",
]

[project.urls]
"Documentation" = "https://github.com/QuantumAudio/Prediction-Coefficient/blob/main/README.md"
"Theory" = "https://medium.com/@LanceDarragh/a-new-type-of-categorical-correlation-coefficient-f5782036fc85"

