[tool.poetry]
name = "wsrouter"
version = "0.7.1"
description = "Starlette Shared WebSocket Endpoint"
documentation = "https://selcouth.gitlab.io/wsrouter/"
authors = ["David Morris <gypsysoftware@gmail.com>"]
license = "MIT"
repository = "https://gitlab.com/selcouth/wsrouter"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Intended Audience :: Developers",
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
]

[tool.poetry.dependencies]
python = "^3.10"
starlette = "^0.20.1"
shortuuid = "^1.0.9"
orjson = "^3.7.1"
boltons = "^21.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
pytest-cov = "^3.0.0"
requests = "^2.27.1"
coveralls = "^3.3.1"
Sphinx = "^5.0.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-autodoc-typehints = "^1.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
