[tool.poetry]
name = "mucalla"
version = "0.0.2"
description = "aggregate results from multiple ethereum contract calls"
authors = ["jin "]

[tool.poetry.dependencies]
python = "^3.8"
web3 = "5.27.0"
eth_retry = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"
black = "^21.12b0"
joblib = "^1.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
