
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-27T11:11:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dda7fe44f1b2f0325dd2102f4aa0dffc796e4327",
 "version": "0.7.1.post.dev660"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
