package:
  name: eden
  version: {{ environ['VERSION'] }}

source:
    path: ../

build:
  script_env:
   - VERSION
   - CONDA_BLD_PATH
   - TRAVIS_PULL_REQUEST
   - TRAVIS_PYTHON_VERSION

requirements:
  build:
      - python
      - dill>=0.2.1
      - future
      - joblib>=0.8.4
      - matplotlib
      - networkx>=2.0
      - numpy>=1.10.4
      - requests
      - requests>=2.7.0
      - scikit-learn>=0.18.2
      - scipy>=0.14.0
      - toolz
  run:
      - python
      - dill>=0.2.1
      - future
      - joblib>=0.8.4
      - matplotlib
      - networkx>=2.0
      - numpy>=1.10.4
      - requests
      - requests>=2.7.0
      - scikit-learn>=0.18.2
      - scipy>=0.14.0
      - toolz

test:
  imports:
    - eden

about:
  home: https://github.com/fabriziocosta/EDeN
  license: MIT
  summary: 'The Explicit Decomposition with Neighborhoods (EDeN) is a decompositional kernel based on the Neighborhood Subgraph Pairwise Distance Kernel (NSPDK) that can be used to induce an explicit feature representation for graphs. This in turn allows the adoption of machine learning algorithm to perform supervised and unsupervised learning task in a scalable way (e.g. using fast stochastic gradient descent methods in classification and approximate neighborhood queries in clustering).'
