[tool.poetry]
name = "datapeek"
version = "0.1.0"
description = "A python package to display data in a more fluent and well formatted manner using colours and smart formatting"
authors = ["lsmucassi <lindasmucassi@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

packages = [
    { include = "src/*" }
]
