
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-23T00:50:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdfb7e5b6cec2184ccd22aa13ffbd09043a4d717",
 "version": "v0.1.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
